head 태그
- 메타 데이터 들어가는 태그

body 태그
- 몸통 태그
- 주요 내용

button 태그
- 버튼 만들어주는 태그

input 태그
- 텍스트를 입력할 텍스트박스를 만들어주는 태그

img 태그
- 이미지 태그

nav 태그
- 웹 문서에서 링크 등의 메뉴 영역

figure 태그
- 동영상, 사진

main 태그
- 본문

footer 태그
- 꼬리말 영역

article 태그
- 기사나 개별 콘텐츠를 담는 영역

div 태그
- 그룹화, 공간을 나누는 블럭

a 태그
- 링크 설정 해주는 태그


### % 라이브러리
beautifulsoup

=> 정적인 페이지 크롤링

selenium, playwright

=> 동적인 페이지 크롤링

In [16]:
%%writefile index.html
<!DOCTYPE html>
<html>
<head>
    <title>나의 손코딩 홈페이지</title>
    <!--
    <link href="./practice.css" rel="stylesheet" type="text/css">
    -->
    <script type="text/javascript" src="add_two_numbers.js"></script>
    <script type="text/javascript" src="what_time_is_it.js"></script>
</head>

<body>
    <nav>
        <a href="./index.html">Home</a>
        <a href="./blog_list.html">Blog</a>
        <a href="./about_me.html">About Me</a>
    </nav>
    <h1>첫번째 크기 헤드라인</h1>
    <h2>두번째 크기 헤드라인</h2>
    <h3>세번째 크기 헤드라인</h3>
    <h4>네번째 크기 헤드라인</h4>
    <h5>다섯번째 크기 헤드라인</h5>

    <button onclick="whatTimeIsIt()">현재시간</button>
    <hr />
    <label for="inputA">a</label>
    <input id="inputA" value=1 onkeyup="doSomething()"> # 숫자 1은 그냥화면에 1을 보여 주기 위함이다.
    <label for="inputB">b</label>
    <input id="inputB" value=2 onkeyup="doSomething()"> # 숫자 2는 그냥 화면에 2를 보여 주기 위함이다.
    <p><span id="valueA">1</span> + <span id="valueB">2</span> = <span id="valueC">3</span>입니다.</p>
    <a href="https://www.google.com">Go to google</a>
    <hr />
    <img src="./stay_funky.jpg" width="600px">
</body>
</html>

Writing index.html

# CSS
선택자 : 선택할 HTML요소를 선택자라고 함

자식선택자
- 직계 자식 요소만 선택하기

- ```css
    ul > li {
        border: 1px solid blue;
    }
    ```

In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [33]:
code_all = pd.read_html('http://kind.krx.co.kr/corpgeneral/corpList.do?method=download', header=0, encoding='euc-kr')

/usr/local/lib/python3.12/dist-packages/bs4/__init__.py:341: UserWarning: You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.
  warnings.warn(

In [19]:
type(code_all)

list

In [20]:
code_all

[           회사명 시장구분    종목코드                   업종  \
 0        보원케미칼  코스닥  0010F0           플라스틱제품 제조업
 1      교보20호스팩  코스닥  0132G0               기타 금융업
 2         인벤테라  코스닥  0007J0      자연과학 및 공학 연구개발업
 3     신한제17호스팩  코스닥  0130D0           금융 지원 서비스업
 4       리센스메디컬  코스닥  394420           의료용 기기 제조업
 ...        ...  ...     ...                  ...
 2764      유한양행   유가  000100              의약품 제조업
 2765    CJ대한통운   유가  000120            도로 화물 운송업
 2766        경방   유가  000050               종합 소매업
 2767     유수홀딩스   유가  000700  회사 본부 및 경영 컨설팅 서비스업
 2768  한진중공업홀딩스   유가  003480    연료용 가스 제조 및 배관공급업

                                                    주요제품         상장일  결산월  \
 0                                차량 내장재용 표면소재, SPC바닥재 등  2026-04-03  12월
 1                                            기업 인수 및 합병  2026-04-02  12월
 2                         철(Fe) 기반 질환 특이성 나노-MRI 조영제 신약  2026-04-02  12월
 3                                             금융지원 서비스업  2026-04-01  12월
 4     피부 냉각마취 의료기기, 경피약물전달 의료기기, 동물용 경피약물전달 의료기기, 안구...  2026-03-31  12월
 ...                                                 ...         ...  ...
 2764  의약품(삐콤씨, 안티푸라민, 렉라자, 로수바미브, 코푸시럽 등), 생활용품(유한락스...  1962-11-01  12월
 2765  Contract Logistics, 포워딩, 항만하역, 해운, 택배국제특송, SCM...  1956-07-02  12월
 2766          섬유류(면사,면혼방사,면직물,면혼방직물,화섬사,화섬직물) 제조,도매,수출입  1956-03-03  12월
 2767                                               지주사업  1956-03-03  12월
 2768                                               지주회사  1956-03-03  12월

                   대표자명                          홈페이지     지역
 0                  허찬회    http://www.bowonchem.co.kr   충청북도
 1                  김서호                           NaN  서울특별시
 2                  신태현           http://inventera.kr  서울특별시
 3                  이효상                           NaN  서울특별시
 4             김건호, 최의경   http://recensmedical.co.kr/    경기도
 ...                ...                           ...    ...
 2764          대표이사 조욱제        http://www.yuhan.co.kr  서울특별시
 2765  신영수, 민영학 (각자 대표)    http://www.cjlogistics.com  서울특별시
 2766            김준, 김담    http://www.kyungbang.co.kr  서울특별시
 2767               송영규  http://www.eusu-holdings.com  서울특별시
 2768               조원국  http://www.hhic-holdings.com    경기도

 [2769 rows x 10 columns]]

In [21]:
len(code_all)

1

In [22]:
df = code_all[0]

In [23]:
df

,회사명,시장구분,종목코드,업종,주요제품,상장일,결산월,대표자명,홈페이지,지역
0,보원케미칼,코스닥,0010F0,플라스틱제품 제조업,"차량 내장재용 표면소재, SPC바닥재 등",2026-04-03,12월,허찬회,http://www.bowonchem.co.kr,충청북도
1,교보20호스팩,코스닥,0132G0,기타 금융업,기업 인수 및 합병,2026-04-02,12월,김서호,NaN,서울특별시
2,인벤테라,코스닥,0007J0,자연과학 및 공학 연구개발업,철(Fe) 기반 질환 특이성 나노-MRI 조영제 신약,2026-04-02,12월,신태현,http://inventera.kr,서울특별시
3,신한제17호스팩,코스닥,0130D0,금융 지원 서비스업,금융지원 서비스업,2026-04-01,12월,이효상,NaN,서울특별시
4,리센스메디컬,코스닥,394420,의료용 기기 제조업,"피부 냉각마취 의료기기, 경피약물전달 의료기기, 동물용 경피약물전달 의료기기, 안구...",2026-03-31,12월,"김건호, 최의경",http://recensmedical.co.kr/,경기도
...,...,...,...,...,...,...,...,...,...,...
2764,유한양행,유가,000100,의약품 제조업,"의약품(삐콤씨, 안티푸라민, 렉라자, 로수바미브, 코푸시럽 등), 생활용품(유한락스...",1962-11-01,12월,대표이사 조욱제,http://www.yuhan.co.kr,서울특별시
2765,CJ대한통운,유가,000120,도로 화물 운송업,"Contract Logistics, 포워딩, 항만하역, 해운, 택배국제특송, SCM...",1956-07-02,12월,"신영수, 민영학 (각자 대표)",http://www.cjlogistics.com,서울특별시
2766,경방,유가,000050,종합 소매업,"섬유류(면사,면혼방사,면직물,면혼방직물,화섬사,화섬직물) 제조,도매,수출입",1956-03-03,12월,"김준, 김담",http://www.kyungbang.co.kr,서울특별시
2767,유수홀딩스,유가,000700,회사 본부 및 경영 컨설팅 서비스업,지주사업,1956-03-03,12월,송영규,http://www.eusu-holdings.com,서울특별시
2768,한진중공업홀딩스,유가,003480,연료용 가스 제조 및 배관공급업,지주회사,1956-03-03,12월,조원국,http://www.hhic-holdings.com,경기도

In [24]:
html = '''
<table>
    <tr><th>이름</th><th>나이</th></tr>
    <tr><td>홍길동</td><td>20</td></tr>
    <tr><td>홍길순</td><td>30</td></tr>
</table>
'''

In [25]:
html

'\n<table>\n    <tr><th>이름</th><th>나이</th></tr>\n    <tr><td>홍길동</td><td>20</td></tr>\n    <tr><td>홍길순</td><td>30</td></tr>\n</table>\n'

In [26]:
from io import StringIO

In [27]:
tables = pd.read_html(StringIO(html))

In [28]:
tables

[    이름  나이
 0  홍길동  20
 1  홍길순  30]

In [29]:
tables[0]

    이름  나이
0  홍길동  20
1  홍길순  30