# yfinance로 주식 불러오기

In [247]:
import yfinance as yf

In [248]:
code = '010130.KS'

In [249]:
import datetime

In [250]:
start = datetime.datetime(2024, 12, 1)

In [251]:
start

datetime.datetime(2024, 12, 1, 0, 0)

In [252]:
end = datetime.datetime(2025, 3, 31)

In [253]:
end

datetime.datetime(2025, 3, 31, 0, 0)

In [254]:
df = yf.download(code, start, end)

/tmp/ipykernel_6512/328843078.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(code, start, end)
[*********************100%***********************]  1 of 1 completed

In [255]:
df

Price              Close          High           Low          Open    Volume
Ticker         010130.KS     010130.KS     010130.KS     010130.KS 010130.KS
Date
2024-12-02  1.380544e+06  1.500889e+06  1.201494e+06  1.208343e+06    133739
2024-12-03  1.508716e+06  1.606558e+06  1.389349e+06  1.418702e+06    116463
2024-12-04  1.634931e+06  1.682874e+06  1.545896e+06  1.569378e+06     85292
2024-12-05  1.956830e+06  1.956830e+06  1.674068e+06  1.693636e+06     95215
2024-12-06  1.773866e+06  2.355045e+06  1.698528e+06  2.078153e+06    250745
...                  ...           ...           ...           ...       ...
2025-03-24  8.062826e+05  8.348323e+05  8.062826e+05  8.269565e+05     13716
2025-03-25  8.112049e+05  8.171118e+05  8.052981e+05  8.082515e+05     14056
2025-03-26  8.358168e+05  8.555062e+05  8.102205e+05  8.171118e+05     20260
2025-03-27  8.259721e+05  8.574752e+05  7.944690e+05  8.397547e+05     29255
2025-03-28  7.541056e+05  8.860248e+05  7.285093e+05  8.358167e+05     65745

[77 rows x 5 columns]

In [256]:
df = df['Close']['010130.KS']

In [257]:
df

Date
2024-12-02    1.380544e+06
2024-12-03    1.508716e+06
2024-12-04    1.634931e+06
2024-12-05    1.956830e+06
2024-12-06    1.773866e+06
                  ...
2025-03-24    8.062826e+05
2025-03-25    8.112049e+05
2025-03-26    8.358168e+05
2025-03-27    8.259721e+05
2025-03-28    7.541056e+05
Name: 010130.KS, Length: 77, dtype: float64

# 네이버 주식 크롤링
- 기사제목 --> 어떤 tag에 쓰여 있는지 알아내기 --> 브라우저의 "개발자 도구 (F12)"를 켜서 찾기
- 기사 본문 링크
- 언론사 이름
- 다음 페이지 수

In [258]:
import requests
from bs4 import BeautifulSoup as bs
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [259]:
base_url = 'https://finance.naver.com/news/news_list.naver'

In [260]:
params_base = {'mode':'LSS2D', 'section_id':'101', 'section_id2':'258'}

In [261]:
page=1
params={**params_base, 'page':page}

In [262]:
params

{'mode': 'LSS2D', 'section_id': '101', 'section_id2': '258', 'page': 1}

In [263]:
response = requests.get(base_url, params=params)

In [264]:
response # 200 정상적으로 끝마쳤다 HTML 상태

In [265]:
response.text

'<!--  global include -->\n\n\t\n\t\n\t\n\t\n<html lang=\'ko\'>\n<head>\n\n\n\t\n\t\n\t\t\n\t\t\t\n\t\t\t\t<title>Npay 증권</title>\n\t\t\t\n\t\t\t\n\t\t\n\t\n\n\n\n\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />\n\n<meta http-equiv="Content-Script-Type" content="text/javascript">\n<meta http-equiv="Content-Style-Type" content="text/css">\n<meta name="apple-mobile-web-app-title" content="Npay 증권" />\n\n\n\n\n\n\t\n    \n        <meta property="og:url" content="http://finance.naver.com/news/news_list.naver?mode=LSS2D&section_id=101&section_id2=258&type=0"/>\n        \n\t\t\t\n\t\t    \n\t\t    \t<meta property="og:title" content="실시간 속보 : Npay 증권"/>\n\t\t     \n\t\t\n\t\t\n\t\t\t\n\t\t\t   <meta property="og:description" content="관심종목의 실시간 주가를 가장 빠르게 확인하는 곳"/>\n\t\t    \n\t\t    \n\t\t\n\t\t \n\t\t\t\n\t\t\t    <meta property="og:image" content="https://ssl.pstatic.net/static/m/stock/im/2016/08/og_stock-200.png"/>\n\t\t    \n\t\t    \n\t\t\n    \n\n<meta property="og:type" content="article"/>\n<meta property="og:article:thumbnailUrl" content=""/>\n<meta property="og:article:author" content="Npay 증권"/>\n<meta property="og:article:author:url" content="http://FINANCE.NAVER.COM"/>\n\n\n\n\n\n\n<link rel=\'stylesheet\' type=\'text/css\' href=\'https://ssl.pstatic.net/imgstock/static.pc/20260406095636/css/finance_header.css\'>\n\n\t\n\t\n\t\n\t\n\t\t\n\t\t<link rel="stylesheet" type="text/css" href="https://ssl.pstatic.net/imgstock/static.pc/20260406095636/css/newstock.css">\n\t\t<link rel="stylesheet" type="text/css" href="https://ssl.pstatic.net/imgstock/static.pc/20260406095636/css/common.css">\n\t\t<link rel="stylesheet" type="text/css" href="https://ssl.pstatic.net/imgstock/static.pc/20260406095636/css/layout.css">\n\t\t<link rel="stylesheet" type="text/css" href="https://ssl.pstatic.net/imgstock/static.pc/20260406095636/css/main.css">\n\t\t<link rel="stylesheet" type="text/css" href="https://ssl.pstatic.net/imgstock/static.pc/20260406095636/css/newstock2.css">\n\t\t<link rel="stylesheet" type="text/css" href="https://ssl.pstatic.net/imgstock/static.pc/20260406095636/css/newstock3.css">\n\t\t<link rel="stylesheet" type="text/css" href="https://ssl.pstatic.net/imgstock/static.pc/20260406095636/css/world.css">\n\t\t<link rel="stylesheet" type="text/css" href="https://ssl.pstatic.net/imgstock/static.pc/20260406095636/css/community.css">\n\t\t\n\t\t\t\n\t\t\t\n\t\t\t\t<script type="text/javascript" src="https://ssl.pstatic.net/imgstock/static.pc/20260406095636/js/jindo.min.ns.1.5.3.euckr.js"></script>\n\t\t\t\t<script type="text/javascript" src="https://ssl.pstatic.net/imgstock/static.pc/20260406095636/js/release/common.js"></script>\n\t\t\t\t<script type="text/javascript" src="https://ssl.pstatic.net/imgstock/static.pc/20260406095636/js/jindoComponent/jindo.Component.1.0.3.js"></script>\n\t\t\t\t<script type="text/javascript" src="https://ssl.pstatic.net/imgstock/static.pc/20260406095636/js/nhn.autocomplete.stock.js"></script>\n\t\t\t\n\t\t\n\n\t\t\n\t\n\n<script>\n\tvar ieVersion = (function () {\n        var version = -1;\n        if (\n          navigator.appName == \'Microsoft Internet Explorer\' &&\n          navigator.userAgent.toLowerCase().indexOf(\'msie\') != -1 &&\n          new RegExp(\'MSIE ([0-9]{1,}[\\./0-9]{0,})\').exec(navigator.userAgent) != null\n        ) {\n          version = parseInt(RegExp.$1);\n        }\n        return version;\n      })();\n</script>\n\t\n\n\t<link rel="shortcut icon" href="https://ssl.pstatic.net/imgstock/favi/favicon.ico" type="image/x-icon">\n\t\n\t<script type="text/javascript">\n    (function(){\n\t\tdocument.write(\n\t\t\t\t[\n\t\t\t\t\t\'<link rel="apple-touch-icon-precomposed" href="https://ssl.pstatic.net/imgstock/favi/favicon-96x96.png"/>\',\n\t\t\t\t\t\'<link rel="apple-touch-icon-precomposed" sizes="180x180" href="https://ssl.pstatic.net/imgstock/favi/favicon-180x180.png"/>\',\n\t\t\t\t\t\'<link rel="apple-touch-icon-precomposed" sizes="192x192" href="https://ssl.pstatic.net/imgstock/favi/favicon-192x192.png"/>\',\n\t\t\t\t\t\'<link rel="icon" type="image/png" sizes="16x16" href="https://ssl.pstatic.net/imgstock/favi/favicon-16x16.png"/>\',\n\t\t\t\t\t\'<link rel="icon" type="image/png" sizes="32x32" href="https://ssl.pstatic.net/imgstock/favi/favicon-32x32.png"/>\',\n\t\t\t\t\t\'<link rel="icon" type="image/png" sizes="96x96" href="https://ssl.pstatic.net/imgstock/favi/favicon-96x96.png"/>\',\n\t\t\t\t\t\'<link rel="icon" type="image/png" sizes="192x192" href="https://ssl.pstatic.net/imgstock/favi/favicon-192x192.png"/>\'\n\t\t\t\t]\n\t\t\t.join(\'\\n\')\n\t\t);\n    })();\n    </script>\n</head>\n\n\n\n\n<body onload=\'getGNB();\'>\n\n\n\n\n<script type="text/javascript">\n\n\n\n\n\n\n\nvar nsc="finance.news";\n\n\nvar ccsrv="cc.naver.com";\n\n\n\t\n\t\n\tvar gnb_service=\'finance\';\n\t\n\n\nvar gnb_logout=document.URL; //GNB에서 로그아웃 후 redirect 될 URL\nvar gnb_searchbox=\'off\'; //미니 검색창을 on 할지 off 할지. default는 off\nvar gnb_shortnick=\'off\'; //닉네임 말줄임(10자)을 on할지 off 할지. default는 off.\n\n\nvar gnb_naverme_layer_open_callback = function(){\n\t   var naverLayerSize = gnbNaverMeLayer.getLayerSize();\n\t\t\n\t\tvar me_layers = document.getElementById("me_layers");\n\t\tme_layers.width=naverLayerSize.width;\n\t\tme_layers.height=naverLayerSize.height;};\n\nvar gnb_naverme_layer_close_callback = function(){\n\t\t\n\t\t\tvar me_layers = document.getElementById("me_layers");\n\t\t\tme_layers.width="0";\n\t\t\tme_layers.height="0";};\n</script>\n\n\n<div id="u_skip">\n\t<a href="#menu" tabindex="1"><span>메인 메뉴로 바로가기</span></a>\n\n\t\n\t\n\t\t<a href="#start" tabindex="2"><span>본문으로 바로가기</span></a>\n\t\n\n</div>\n\n\n<div id="header">\n\t<div class="header_area">\n\t\t<div class="header_inner">\n\t\t\t<div class="logo_area">\n\t\t\t\t<h1 class="service">\n\t\t\t\t\t<a href="https://www.naver.com/" class="logo_link" onClick="clickcr(this, \'STA.naver\', \'\', \'\', event);">\n\t\t\t\t\t\t<svg width="22" height="22" viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">\n\t\t\t\t\t\t\t<path d="M22 11C22 13.1756 21.3549 15.3023 20.1462 17.1113C18.9375 18.9202 17.2195 20.3301 15.2095 21.1627C13.1995 21.9952 10.9878 22.2131 8.85401 21.7886C6.72022 21.3642 4.76021 20.3166 3.22183 18.7782C1.68345 17.2398 0.635805 15.2798 0.211368 13.146C-0.213069 11.0122 0.00476298 8.80047 0.837327 6.79048C1.66989 4.78049 3.07979 3.06253 4.88873 1.85383C6.69768 0.645137 8.82441 0 11 0C13.9174 0 16.7153 1.15893 18.7782 3.22183C20.8411 5.28473 22 8.08262 22 11ZM12.8398 5.83V11.3602L8.98976 5.83H5.83V16.1838H9.1575V10.637L13.0075 16.17H16.1783V5.83H12.8398Z" fill="#000"/>\n\t\t\t\t\t\t</svg>\n\t\t\t\t\t\t<span class="blind">네이버</span>\n\t\t\t\t\t</a>\n\t\t\t\t\t<a href="https://new-m.pay.naver.com/" class="logo_link" onClick="clickcr(this, \'STA.pay\', \'\', \'\', event);">\n\t\t\t\t\t\t<svg width="37" height="22" viewBox="0 0 37 22" fill="none" xmlns="http://www.w3.org/2000/svg">\n\t\t\t\t\t\t\t<path d="M34.4319 5.21944L31.3913 12.1478L27.9518 5.21944H25.3072L30.1783 14.8317L28.1703 19.3358H30.7384L37 5.2331L34.4319 5.21944ZM23.6171 15.9331H21.1037V14.9328C20.1894 15.7342 19.0108 16.1685 17.7953 16.1518C14.7901 16.1518 12.4379 13.692 12.4379 10.5763C12.4379 7.46057 14.7874 5.00079 17.7953 5.00079C19.0104 4.9833 20.189 5.41657 21.1037 6.21701V5.21944H23.6171V15.9331ZM21.3987 10.5899C21.3987 8.57019 19.9891 7.03694 18.1204 7.03694C16.2517 7.03694 14.842 8.57019 14.842 10.5899C14.842 12.6097 16.249 14.1429 18.1204 14.1429C19.9918 14.1429 21.3987 12.596 21.3987 10.5899ZM0.00819554 19.3358H2.63088V15.023C3.52823 15.7695 4.66309 16.1699 5.83001 16.1518C8.83516 16.1518 11.1901 13.692 11.1901 10.5763C11.1901 7.46057 8.83789 5.00079 5.83001 5.00079C4.61166 4.9789 3.42899 5.4126 2.51341 6.21701V5.21944H0L0.00819554 19.3358ZM5.51856 7.03694C7.38722 7.03694 8.79691 8.57019 8.79691 10.5899C8.79691 12.6097 7.38722 14.1429 5.51856 14.1429C3.6499 14.1429 2.24021 12.6097 2.24021 10.5899C2.24021 8.57019 3.63351 7.03694 5.51856 7.03694Z" fill="#000"/>\n\t\t\t\t\t\t</svg>\n\t\t\t\t\t\t<span class="blind">페이</span>\n\t\t\t\t\t</a>\n\t\t\t\t\t<a href="/" class="logo_link" onClick="clickcr(this, \'STA.finance\', \'\', \'\', event);">\n\t\t\t\t\t\t<svg width="34" height="22" viewBox="0 0 34 22" fill="none" xmlns="http://www.w3.org/2000/svg">\n\t\t\t\t\t\t\t<path d="M2.43006 8.88998L1.85406 6.99998C5.29206 6.31598 7.00206 5.34398 7.45206 4.31798H2.71806V2.35598H14.3641V4.31798H9.75606C9.70206 4.65998 9.61206 4.98398 9.46806 5.28998L15.2101 6.98198L14.4901 8.88998L8.02806 6.92798C6.84006 7.75598 5.00406 8.40398 2.43006 8.88998ZM0.612061 11.5V9.53798H16.4521V11.5H0.612061ZM6.53406 12.796H10.5301C13.2301 12.796 14.7961 14.128 14.7961 15.91C14.7961 17.71 13.2301 19.024 10.5301 19.024H6.53406C3.85206 19.024 2.28606 17.71 2.28606 15.91C2.28606 14.128 3.85206 12.796 6.53406 12.796ZM6.96606 17.044H10.1161C11.7901 17.044 12.4921 16.594 12.4921 15.892C12.4921 15.19 11.7901 14.776 10.1161 14.776H6.96606C5.29206 14.776 4.57206 15.19 4.57206 15.892C4.57206 16.594 5.29206 17.044 6.96606 17.044Z" fill="#000"/>\n\t\t\t\t\t\t\t<path d="M25.1904 13.354V11.536H29.4564V2.03198H31.7604V15.334H29.4564V13.354H25.1904ZM21.3384 10.564C20.9244 10.582 20.5464 10.582 20.1684 10.582H17.4504L17.3604 8.61998H20.3844C21.5004 8.61998 22.9584 8.56598 24.4884 8.45798C24.7224 6.99998 24.8484 5.63198 24.8664 4.62398H18.4404V2.66198H27.0984V3.56198C27.0984 5.16398 26.9724 6.76598 26.7564 8.25998L28.2684 8.09798L28.5024 10.006C26.9724 10.222 25.2264 10.384 23.5704 10.474C23.4984 11.5 23.3904 12.562 23.2644 13.714L21.0684 13.588C21.1764 12.508 21.2664 11.536 21.3384 10.564ZM22.4724 14.254V16.756H32.3724V18.844H20.1684V14.254H22.4724Z" fill="#000"/>\n\t\t\t\t\t\t</svg>\n\t\t\t\t\t\t<span class="blind">증권</span>\n\t\t\t\t\t</a>\n\t\t\t\t</h1>\n\t\t\t</div>\n\n\t\t\t<div class="right_area">\n\t\t\t\t<div class="search_area">\n\t\t\t\t\t<form name="search" action="/search/search.naver"  method="get" onsubmit="return delayed_submit(this)" style="margin:0; padding:0;">\n\t\t\t\t\t<label for="stock_items" class="blind">증권 종목명·지수명 검색</label>\n\t\t\t\t\t<input type="text" id="stock_items" name="query" title="종목명·지수명 검색" class="search_input" placeholder="종목명&middot;지수명 입력" accesskey="s" autocomplete="off">\n\t\t\t\t\t<input type="hidden" id="_endUrl" name="endUrl" value="" />\n\t\t\t\t\t\n\t\t\t\t\t\t\n\t\t\t\t\t\t<button type="submit" class="search_button" onclick="clickcr(this, \'STA.search\', \'\', \'\', event);">\n\t\t\t\t\t\t<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">\n\t\t\t\t\t\t\t<path fill-rule="evenodd" clip-rule="evenodd" d="M6.9999 2.59996C4.56985 2.59996 2.5999 4.56991 2.5999 6.99996C2.5999 9.43002 4.56985 11.4 6.9999 11.4C9.42996 11.4 11.3999 9.43002 11.3999 6.99996C11.3999 4.56991 9.42996 2.59996 6.9999 2.59996ZM1.3999 6.99996C1.3999 3.90717 3.90711 1.39996 6.9999 1.39996C10.0927 1.39996 12.5999 3.90717 12.5999 6.99996C12.5999 10.0928 10.0927 12.6 6.9999 12.6C3.90711 12.6 1.3999 10.0928 1.3999 6.99996Z" fill="#404048"></path>\n\t\t\t\t\t\t\t<path fill-rule="evenodd" clip-rule="evenodd" d="M10.2421 10.2424C10.4765 10.0081 10.8564 10.0081 11.0907 10.2424L14.424 13.5758C14.6583 13.8101 14.6583 14.19 14.424 14.4243C14.1897 14.6586 13.8098 14.6586 13.5755 14.4243L10.2421 11.091C10.0078 10.8567 10.0078 10.4768 10.2421 10.2424Z" fill="#404048"></path>\n\t\t\t\t\t\t</svg>\n\t\t\t\t\t\t<span class="blind">검색</span>\n\t\t\t\t\t</button>\n\t\t\t\t\t<div class="auto_area">\n\t\t\t\t\t\t<span class="blind">자동완성</span>\n\t\t\t\t\t\t<div id="autoFrame" style="display: none;">\n\t\t\t\t\t\t\t<div class="wrap" id="atcmp" style="display:none;">\n\t\t\t\t\t\t\t\t<div class="wrap_in">\n\t\t\t\t\t\t\t\t\t<div class="words">\n\t\t\t\t\t\t\t\t\t\t<ul class="_resultBox">\n\t\t\t\t\t\t\t\t\t\t\t<li>\n\t\t\t\t\t\t\t\t\t\t\t\t<a href="#" onclick="clickcr(this, \'AUT.list\', \'\', \'\', event); return false;" class="_au_real_list">\n\t\t\t\t\t\t\t\t\t\t\t\t\t<span class="num _au_real_list">@code@</span>\n\t\t\t\t\t\t\t\t\t\t\t\t\t<span class="_au_real_list">@txt@</span>\n\t\t\t\t\t\t\t\t\t\t\t\t\t<span class="type _au_real_list">@market@</span>\n\t\t\t\t\t\t\t\t\t\t\t\t</a>\n\t\t\t\t\t\t\t\t\t\t\t\t<div style="display:none" class="_au_full">@full_txt@</div>\n\t\t\t\t\t\t\t\t\t\t\t\t<div style="display:none" class="_au_code">@in_code@</div>\n\t\t\t\t\t\t\t\t\t\t\t\t<div style="display:none" class="_au_name">@in_name@</div>\n\t\t\t\t\t\t\t\t\t\t\t\t<div style="display:none" class="_au_link">@in_link@</div>\n\t\t\t\t\t\t\t\t\t\t\t\t<div style="display:none" class="_au_market">@in_market@</div>\n\t\t\t\t\t\t\t\t\t\t\t</li>\n\t\t\t\t\t\t\t\t\t\t</ul>\n\t\t\t\t\t\t\t\t\t\t<div class="search_notice">\n\t\t\t\t\t\t\t\t\t\t\t<p class="text">\n\t\t\t\t\t\t\t\t\t\t\t\t공모주와 해외 종목은 모바일 페이지로 이동합니다.\n\t\t\t\t\t\t\t\t\t\t\t</p>\n\t\t\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t<!-- 현재 자동완성 기능을 사용하고 계십니다 -->\n\t\t\t\t\t\t\t\t<div class="wrap" id="atcmpIng" style="display:none;">\n\t\t\t\t\t\t\t\t\t<div class="wrap_in">\n\t\t\t\t\t\t\t\t\t\t<div class="words">\n\t\t\t\t\t\t\t\t\t\t\t<p class="msg">\n\t\t\t\t\t\t\t\t\t\t\t\t현재 자동완성 기능을 사용하고 계십니다.\n\t\t\t\t\t\t\t\t\t\t\t</p>\n\t\t\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t<!--// 현재 자동완성 기능을 사용하고 계십니다 -->\n\t\t\t\t\t\t\t\t<!-- 자동완성 기능이 활성화 -->\n\t\t\t\t\t\t\t\t<div class="wrap" id="atcmpStart" style="display:none;">\n\t\t\t\t\t\t\t\t\t<div class="wrap_in">\n\t\t\t\t\t\t\t\t\t\t<div class="words">\n\t\t\t\t\t\t\t\t\t\t\t<p class="msg">\n\t\t\t\t\t\t\t\t\t\t\t\t자동완성 기능이 활성화되었습니다.\n\t\t\t\t\t\t\t\t\t\t\t</p>\n\t\t\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t</div>\n\t\t\t\t\t</div>\n\t\t\t\t\t</form>\n\t\t\t\t</div>\n\t\t\t\t<div class="gnb_area">\n\t\t\t\t\t<div id="gnb">\n\t\t\t\t\t\t<script charset="EUC-KR" type="text/javascript">\n\t\t\t\t\t\t\tvar gnb_service = "finance";\n\t\t\t\t\t\t\tvar gnb_template = location.protocol === "http:" ? "gnb_quirks_euckr" : "gnb_utf8" ;\n\t\t\t\t\t\t\tvar gnb_logout=encodeURIComponent(location.href);\n\t\t\t\t\t\t\tvar gnb_brightness = 1;\n\t\t\t\t\t\t\tvar gnb_one_naver = 0;\n\t\t\t\t\t\t</script>\n\t\t\t\t\t\t<script type="text/javascript" charset="utf-8" src="https://ssl.pstatic.net/static.gn/templates/gnb_utf8.nhn?20260414">\n\t\t\t\t\t\t</script>\n\t\t\t\t\t</div>\n\t\t\t\t</div>\n\t\t\t</div>\n\t\t</div>\n\t</div>\n\t<div class="lnb_area ">\n\t\t<div class="lnb_inner">\n\t\t\t<div id="menu">\n\t\t\t\t<ul class="menu">\n\t\t\t\t\t<li class="m1 first "><a href="/" onClick="clickcr(this, \'LNB.home\', \'\', \'\', event);"><span class="tx">증권 홈</span></a></li>\n\t\t\t\t\t<li class="m2 "><a href="/sise/" onClick="clickcr(this, \'LNB.sise\', \'\', \'\', event);"><span class="tx">국내증시</span></a></li>\n\t\t\t\t\t<li class="m3 "><a href="/world/" onClick="clickcr(this, \'LNB.world\', \'\', \'\', event);"><span class="tx">해외증시</span></a></li>\n\t\t\t\t\t<li class="m4 "><a href="/marketindex/" onClick="clickcr(this, \'LNB.market\', \'\', \'\', event);"><span class="tx">시장지표</span></a></li>\n\t\t\t\t\t<li class="m6 "><a href="/research/" onClick="clickcr(this, \'LNB.research\', \'\', \'\', event);"><span class="tx">리서치</span></a></li>\n\t\t\t\t\t<li class="m7 on"><a href="/news/"><span class="tx">뉴스</span><span class="blind">선택됨</span></a></li>\n\t\t\t\t\t<li class="m8 "><a href="/mystock/" onClick="clickcr(this, \'LNB.mystock\', \'\', \'\', event);"><span class="tx">MY</span></a></li>\n\t\t\t\t</ul>\n\t\t\t\t<!-- 새로운 증권보기 버튼 -->\n\t\t\t\t<div class="area_stock_button">\n\t\t\t\t\t<a href="https://stock.naver.com" class="link_new">\n\t\t\t\t\t\t<span class="icon_refresh"></span>\n\t\t\t\t\t\t새로운 증권 보기\n\t\t\t\t\t\t<span class="icon_new">\n\t\t\t\t\t\t\t<span class="blind">NEW</span>\n\t\t\t\t\t\t</span>\n\t\t\t\t\t</a>\n\t\t\t\t\t<span class="tooltip">\n\t\t\t\t\t\t더 편리해진 증권을 만나보세요\n\t\t\t\t\t\t<span class="icon_arrow"></span>\n\t\t\t\t\t</span>\n\t\t\t\t</div>\n\t\t\t\t<!-- //새로운 증권보기 버튼 -->\n\t\t\t</div>\n\t\t</div>\n\t</div>\n\t\n\t\n\t\n\t\n\n\t\n\t<script type="text/JavaScript">\n\t\t/* lcs 집계 */\n        ;(function(){\n            var eventType = "onpageshow" in window ? "pageshow" : "load";\n            jindo.$Fn(function(){\n                lcs_do();\n            }).attach(window, eventType);\n        })();\n\n\t\t/* 검색 자동완성 [ 인자1 : 검색input의 ID, 인자2 : iframe 태그 ID ]   */\n\t\t// AutoComplete 생성\n\t\tvar acDomain = "ac.stock.naver.com";\n\t\tif (location.hostname.indexOf("staging-") > -1) {\n\t\t\tacDomain = "staging-" + acDomain;\n\t\t} else if (location.hostname.indexOf("test-") > -1) {\n\t\t\tacDomain = "test-" + acDomain;\n\t\t} else if (location.hostname.indexOf("dev-") > -1 || location.hostname.indexOf("localhost") > -1 || location.hostname.indexOf("local-") > -1) {\n\t\t\tacDomain = "dev-" + acDomain;\n\t\t}\n\n        var acUrl = "https://" + acDomain + "/ac";\n\n\t\tsmartSearch = new nhn.Autocomplete(\n\t\t\t// InputManager 생성\n\t\t\tnew nhn.AcInputManager(jindo.$("stock_items")),\n\t\t\t// DataManager 생성\n\t\t\tnew nhn.AcDataManager(acUrl, "xhr", "get", {}),\n\t\t\t// ViewManager 생성\n\t\t\tnew nhn.AcStockViewManager(jindo.$("autoFrame"), jindo.$("nautocomplete"), {\n                                        strMax: 200,\n                                        listMax: [7, 2, 2],\n                                        aRedirectUrl: [\n\t\t\t\t\t\t\t\t\t\t"https://" + window.location.hostname,\n                            \t\t\t"https://finance.naver.com",\n                            \t\t\t"https://finance.naver.com"],\n\t\t\t\t\t\t\t\t\t\tmobileUrl: "https://m.stock.naver.com"}),\n\t\t\t// Autocomplete Option\n            {formId:"search", cookieDomain:location.hostname, cookieName:"NaverCommonStock_disable"});\n\n\t\t\tsmartSearch.attach({\n\t            onFocus: function () {\n\t                var weInput = jindo.$Element(\'stock_items\');\n\t                if (weInput && weInput.hasClass("snb_default")) {\n\t                        weInput.text("");\n\t                        weInput.removeClass(\'snb_default\');\n\t                }\n\t            }\n\t        });\n\n\t\t/* 통합검색  start ----->  */\n\t\tvar sSearchHintText = \'종목명·지수명·환율명·원자재명 입력\';\n\t\tfunction itegrationSearch() {\n\t\t\tvar query = jindo.$(\'stock_items\').value;\n\n\t\t\tif ( query == \'\'  || encodeURIComponent(query) == encodeURIComponent(sSearchHintText))\n\t\t\t{\n\t\t\t\talert ( \'검색어를 입력해 주세요.\' );\n\t\t\t\treturn;\n\t\t\t}\n\n            var url = "https://search.naver.com/search.naver?sm=sta_hty.finance&where=nexearch&ie=UTF8&query=" + encodeURIComponent(query);\n            window.open(url, "_blank");\n\n\t\t\treturn false;\n\t\t}\n\n\t\tfunction delayed_submit(object) {\n\t\t\tif (navigator.userAgent.indexOf(\'MSIE\') == -1) {\n\t\t\t\twindow.setTimeout(function() {stock_search(object)}, 300);\n\t\t\t} else {\n\t\t\t\tstock_search(object);\n\t\t\t}\n\t\t\treturn false;\n\t\t}\n\n\t\tfunction stock_search (object) {\n\t\t\t// endUrl check\n\t\t\tif (object.endUrl.value) {\n\t\t\t\tif (object.endUrl.value.startsWith("https://m.stock.naver.com")) {\n\t\t\t\t\t// 검색정보 초기화\n\t\t\t\t\tvar _endUrl = object.endUrl.value;\n\t\t\t\t\tobject.query.value = "";\n\t\t\t\t\tobject.endUrl.value = "";\n\t\t\t\t\tdocument.getElementById("atcmp").style.display="none";\n\t\t\t\t\twindow.open(_endUrl, "_blank");\n\t\t\t\t} else {\n\t\t\t\t\tlocation.href = object.endUrl.value;\n\t\t\t\t}\n\n\t\t\t\treturn;\n\t\t\t}\n\n\t\t\t// query check\n\t\t\tquery = object.query.value.replace(/^\\s*/,\'\').replace(/\\s*$/,\'\');\t// trim\n\t\t\tobject.query.value=query;\n\n\t\t\tif ( query == \'\' || query == sSearchHintText.replace(/^\\s*/,\'\').replace(/\\s*$/,\'\'))\n\t\t\t{\n\t\t\t\talert ( \'검색어를 입력해 주세요.\' );\n\t\t\t\treturn;\n\t\t\t}\n\t\t\telse {\n\t\t\t\tobject.submit();\n\t\t\t}\n\t\t}\n\t\t/* <---------- 통합검

In [266]:
soup = bs(response.text, 'html.parser') # html 문서로 고쳐준다

## bs
: 주어진 텍스트 구조를 분석해서
- html & xml 문서처럼 사용할 수 있게 해준다.
- 크롤링 기능 제공 => 이걸 보고 parsing이라 함

In [267]:
soup.select('.articleSubject')

[<dd class="articleSubject">
 <a href="/news/news_read.naver?article_id=0006257135&amp;office_id=018&amp;mode=LSS2D&amp;type=0§ion_id=101§ion_id2=258§ion_id3=&amp;date=20260414&amp;page=1" title="[속보]코스피, 2.74% 오른 5967.75...코스닥, 2.0% 상승 마감">[속보]코스피, 2.74% 오른 5967.75...코스닥, 2.0% 상승 마감</a>
 </dd>,
 <dd class="articleSubject">
 <a href="/news/news_read.naver?article_id=0004610586&amp;office_id=011&amp;mode=LSS2D&amp;type=0§ion_id=101§ion_id2=258§ion_id3=&amp;date=20260414&amp;page=1" title="위험선호 확산 vs 결제수요…환율 1480원대 공방 [김혜란의 FX]">위험선호 확산 vs 결제수요…환율 1480원대 공방 [김혜란의 FX]</a>
 </dd>,
 <dd class="articleSubject">
 <a href="/news/news_read.naver?article_id=0008889145&amp;office_id=421&amp;mode=LSS2D&amp;type=0§ion_id=101§ion_id2=258§ion_id3=&amp;date=20260414&amp;page=1" title="코스피,  2.74% 상승한 5967.75 마감…코스닥 2.00%↑(2보)">코스피,  2.74% 상승한 5967.75 마감…코스닥 2.00%↑(2보)</a>
 </dd>,
 <dd class="articleSubject">
 <a href="/news/news_read.naver?article_id=0005274805&amp;office_id=015&amp;mode=LSS2D&amp;type=0§ion_id=101§ion_id2=258§ion_id3=&amp;date=20260414&amp;page=1" title="외국인 현·선물 2.7조 순매수에…'육천피' 턱밑까지">외국인 현·선물 2.7조 순매수에…'육천피' 턱밑까지</a>
 </dd>,
 <dd class="articleSubject">
 <a href="/news/news_read.naver?article_id=0000854953&amp;office_id=422&amp;mode=LSS2D&amp;type=0§ion_id=101§ion_id2=258§ion_id3=&amp;date=20260414&amp;page=1" title="코스피, 2.74% 오른 5,967.75 마감…코스닥도 2%↑">코스피, 2.74% 오른 5,967.75 마감…코스닥도 2%↑</a>
 </dd>,
 <dd class="articleSubject">
 <a href="/news/news_read.naver?article_id=0008889132&amp;office_id=421&amp;mode=LSS2D&amp;type=0§ion_id=101§ion_id2=258§ion_id3=&amp;date=20260414&amp;page=1" title="[달러·원] 환율 8.1원 내 1481.2원 마감">[달러·원] 환율 8.1원 내 1481.2원 마감</a>
 </dd>,
 <dd class="articleSubject">
 <a href="/news/news_read.naver?article_id=0008889128&amp;office_id=421&amp;mode=LSS2D&amp;type=0§ion_id=101§ion_id2=258§ion_id3=&amp;date=20260414&amp;page=1" title="[코스닥] 22.04p(2.00%) 오른 1121.88 마감">[코스닥] 22.04p(2.00%) 오른 1121.88 마감</a>
 </dd>,
 <dd class="articleSubject">
 <a href="/news/news_read.naver?article_id=0008889118&amp;office_id=421&amp;mode=LSS2D&amp;type=0§ion_id=101§ion_id2=258§ion_id3=&amp;date=20260414&amp;page=1" title="[코스피] 159.12p(2.74%) 오른 5967.74 마감">[코스피] 159.12p(2.74%) 오른 5967.74 마감</a>
 </dd>,
 <dd class="articleSubject">
 <a href="/news/news_read.naver?article_id=0001248975&amp;office_id=215&amp;mode=LSS2D&amp;type=0§ion_id=101§ion_id2=258§ion_id3=&amp;date=20260414&amp;page=1" title="[속보] 6,000선 턱밑…SK하이닉스6%·스퀘어 10%↑">[속보] 6,000선 턱밑…SK하이닉스6%·스퀘어 10%↑</a>
 </dd>,
 <dd class="articleSubject">
 <a href="/news/news_read.naver?article_id=0005507536&amp;office_id=014&amp;mode=LSS2D&amp;type=0§ion_id=101§ion_id2=258§ion_id3=&amp;date=20260414&amp;page=1" title="차바이오F&amp;C, 반려동물 영양제 '펫세븐 장 케어 유산균' 출시">차바이오F&amp;C, 반려동물 영양제 '펫세븐 장 케어 유산균' 출시</a>
 </dd>,
 <dd class="articleSubject">
 <a href="/news/news_read.naver?article_id=0016021047&amp;office_id=001&amp;mode=LSS2D&amp;type=0§ion_id=101§ion_id2=258§ion_id3=&amp;date=20260414&amp;page=1" title="코스피, 장중 '6천피' 찍고 5,960선 마감…코스닥도 올라">코스피, 장중 '6천피' 찍고 5,960선 마감…코스닥도 올라</a>
 </dd>,
 <dt class="articleSubject">
 <a href="/news/news_read.naver?article_id=0013886989&amp;office_id=003&amp;mode=LSS2D&amp;type=0§ion_id=101§ion_id2=258§ion_id3=&amp;date=20260414&amp;page=1" title="코스피 5967.75(▲2.74%), 코스닥 1121.88(▲2.00%), 원·달러 환율 1481.2원(▼8.1원) 마감[시황]">코스피 5967.75(▲2.74%), 코스닥 1121.88(▲2.00%), 원·달러 환율 ..</a>
 </dt>,
 <dd class="articleSubject">
 <a href="/news/news_read.naver?article_id=0004610584&amp;office_id=011&amp;mode=LSS2D&amp;type=0§ion_id=101§ion_id2=258§ion_id3=&amp;date=20260414&amp;page=1" title="[코스피] 159.13포인트(2.74%) 오른 5967.75 마감">[코스피] 159.13포인트(2.74%) 오른 5967.75 마감</a>
 </dd>,
 <dd class="articleSubject">
 <a href="/news/news_read.naver?article_id=0001138957&amp;office_id=417&amp;mode=LSS2D&amp;type=0§ion_id=101§ion_id2=258§ion_id3=&amp;date=20260414&amp;page=1" title="[속보] 코스닥 1121.88…2.00% 상승 마감">[속보] 코스닥 1121.88…2.00% 상승 마감</a>
 </dd>,
 <dd class="articleSubject">
 <a href="/news/news_read.naver?article_id=0016021042&amp;office_id=001&amp;mode=LSS2D&amp;type=0§ion_id=101§ion_id2=258§ion_id3=&amp;date=20260414&amp;page=1" title="키움證 로보어드바이저 '키움모멘텀', 1년 수익률 최고수준 기록">키움證 로보어드바이저 '키움모멘텀', 1년 수익률 최고수준 기록</a>
 </dd>,
 <dt class="articleSubject">
 <a href="/news/news_read.naver?article_id=0005749340&amp;office_id=277&amp;mode=LSS2D&amp;type=0§ion_id=101§ion_id2=258§ion_id3=&amp;date=20260414&amp;page=1" title="코스닥 22.04P 오른 1121.88 마감(2.0%↑)">코스닥 22.04P 오른 1121.88 마감(2.0%↑)</a>
 </dt>,
 <dd class="articleSubject">
 <a href="/news/news_read.naver?article_id=0004610583&amp;office_id=011&amp;mode=LSS2D&amp;type=0§ion_id=101§ion_id2=258§ion_id3=&amp;date=20260414&amp;page=1" title="[코스닥] 22.04포인트(2.00%) 오른 1121.88 마감">[코스닥] 22.04포인트(2.00%) 오른 1121.88 마감</a>
 </dd>,
 <dd class="articleSubject">
 <a href="/news/news_read.naver?article_id=0013886984&amp;office_id=003&amp;mode=LSS2D&amp;type=0§ion_id=101§ion_id2=258§ion_id3=&amp;date=20260414&amp;page=1" title="[속보]코스피, 협상 기대 속 2.74% 오른 5967.75 마감">[속보]코스피, 협상 기대 속 2.74% 오른 5967.75 마감</a>
 </dd>,
 <dt class="articleSubject">
 <a href="/news/news_read.naver?article_id=0005749339&amp;office_id=277&amp;mode=LSS2D&amp;type=0§ion_id=101§ion_id2=258§ion_id3=&amp;date=20260414&amp;page=1" title="코스피 159.13P 오른 5967.75 마감(2.74%↑)">코스피 159.13P 오른 5967.75 마감(2.74%↑)</a>
 </dt>,
 <dd class="articleSubject">
 <a href="/news/news_read.naver?article_id=0001138955&amp;office_id=417&amp;mode=LSS2D&amp;type=0§ion_id=101§ion_id2=258§ion_id3=&amp;date=20260414&amp;page=1" title="[속보] 코스피 5967.74…2.74% 상승 마감">[속보] 코스피 5967.74…2.74% 상승 마감</a>
 </dd>]

In [268]:
type(soup.select('.articleSubject'))

bs4.element.ResultSet

In [269]:
articlesubject_list = soup.select('.articleSubject')
len(articlesubject_list)

20

In [270]:
articlesubject_list[0]

<dd class="articleSubject">
<a href="/news/news_read.naver?article_id=0006257135&amp;office_id=018&amp;mode=LSS2D&amp;type=0§ion_id=101§ion_id2=258§ion_id3=&amp;date=20260414&amp;page=1" title="[속보]코스피, 2.74% 오른 5967.75...코스닥, 2.0% 상승 마감">[속보]코스피, 2.74% 오른 5967.75...코스닥, 2.0% 상승 마감</a>
</dd>

In [271]:
articlesubject_list[0].select_one('a').get_text()

'[속보]코스피, 2.74% 오른 5967.75...코스닥, 2.0% 상승 마감'

In [272]:
for i in range(len(articlesubject_list)):
    title = articlesubject_list[i].select_one('a').get_text()
    print(title)

[속보]코스피, 2.74% 오른 5967.75...코스닥, 2.0% 상승 마감
위험선호 확산 vs 결제수요…환율 1480원대 공방 [김혜란의 FX]
코스피,  2.74% 상승한 5967.75 마감…코스닥 2.00%↑(2보)
외국인 현·선물 2.7조 순매수에…'육천피' 턱밑까지
코스피, 2.74% 오른 5,967.75 마감…코스닥도 2%↑
[달러·원] 환율 8.1원 내 1481.2원 마감
[코스닥] 22.04p(2.00%) 오른 1121.88 마감
[코스피] 159.12p(2.74%) 오른 5967.74 마감
[속보] 6,000선 턱밑…SK하이닉스6%·스퀘어 10%↑
차바이오F&C, 반려동물 영양제 '펫세븐 장 케어 유산균' 출시
코스피, 장중 '6천피' 찍고 5,960선 마감…코스닥도 올라
코스피 5967.75(▲2.74%), 코스닥 1121.88(▲2.00%), 원·달러 환율 ..
[코스피] 159.13포인트(2.74%) 오른 5967.75 마감
[속보] 코스닥 1121.88…2.00% 상승 마감
키움證 로보어드바이저 '키움모멘텀', 1년 수익률 최고수준 기록
코스닥 22.04P 오른 1121.88 마감(2.0%↑)
[코스닥] 22.04포인트(2.00%) 오른 1121.88 마감
[속보]코스피, 협상 기대 속 2.74% 오른 5967.75 마감
코스피 159.13P 오른 5967.75 마감(2.74%↑)
[속보] 코스피 5967.74…2.74% 상승 마감

In [273]:
for i in articlesubject_list:
    title = i.select_one('a').get_text()
    print(title)

[속보]코스피, 2.74% 오른 5967.75...코스닥, 2.0% 상승 마감
위험선호 확산 vs 결제수요…환율 1480원대 공방 [김혜란의 FX]
코스피,  2.74% 상승한 5967.75 마감…코스닥 2.00%↑(2보)
외국인 현·선물 2.7조 순매수에…'육천피' 턱밑까지
코스피, 2.74% 오른 5,967.75 마감…코스닥도 2%↑
[달러·원] 환율 8.1원 내 1481.2원 마감
[코스닥] 22.04p(2.00%) 오른 1121.88 마감
[코스피] 159.12p(2.74%) 오른 5967.74 마감
[속보] 6,000선 턱밑…SK하이닉스6%·스퀘어 10%↑
차바이오F&C, 반려동물 영양제 '펫세븐 장 케어 유산균' 출시
코스피, 장중 '6천피' 찍고 5,960선 마감…코스닥도 올라
코스피 5967.75(▲2.74%), 코스닥 1121.88(▲2.00%), 원·달러 환율 ..
[코스피] 159.13포인트(2.74%) 오른 5967.75 마감
[속보] 코스닥 1121.88…2.00% 상승 마감
키움證 로보어드바이저 '키움모멘텀', 1년 수익률 최고수준 기록
코스닥 22.04P 오른 1121.88 마감(2.0%↑)
[코스닥] 22.04포인트(2.00%) 오른 1121.88 마감
[속보]코스피, 협상 기대 속 2.74% 오른 5967.75 마감
코스피 159.13P 오른 5967.75 마감(2.74%↑)
[속보] 코스피 5967.74…2.74% 상승 마감

In [274]:
i.select_one('a')

<a href="/news/news_read.naver?article_id=0001138955&amp;office_id=417&amp;mode=LSS2D&amp;type=0§ion_id=101§ion_id2=258§ion_id3=&amp;date=20260414&amp;page=1" title="[속보] 코스피 5967.74…2.74% 상승 마감">[속보] 코스피 5967.74…2.74% 상승 마감</a>

In [275]:
'https://finance.naver.com'+i.select_one('a').get('href', '')

'https://finance.naver.com/news/news_read.naver?article_id=0001138955&office_id=417&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1'

In [276]:
for i in articlesubject_list:
    a_tag = i.select_one('a')
    title = a_tag.get_text(strip=True)
    link = 'https://finance.naver.com'+a_tag.get('href', '')
    print(title)
    print(link)
    print()

[속보]코스피, 2.74% 오른 5967.75...코스닥, 2.0% 상승 마감
https://finance.naver.com/news/news_read.naver?article_id=0006257135&office_id=018&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1

위험선호 확산 vs 결제수요…환율 1480원대 공방 [김혜란의 FX]
https://finance.naver.com/news/news_read.naver?article_id=0004610586&office_id=011&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1

코스피,  2.74% 상승한 5967.75 마감…코스닥 2.00%↑(2보)
https://finance.naver.com/news/news_read.naver?article_id=0008889145&office_id=421&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1

외국인 현·선물 2.7조 순매수에…'육천피' 턱밑까지
https://finance.naver.com/news/news_read.naver?article_id=0005274805&office_id=015&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1

코스피, 2.74% 오른 5,967.75 마감…코스닥도 2%↑
https://finance.naver.com/news/news_read.naver?article_id=0000854953&office_id=422&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1

[달러·원] 환율 8.1원 내 1481.2원 마감
https://finance.naver.com/news/news_read.naver?article_id=0008889132&office_id=421&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1

[코스닥] 22.04p(2.00%) 오른 1121.88 마감
https://finance.naver.com/news/news_read.naver?article_id=0008889128&office_id=421&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1

[코스피] 159.12p(2.74%) 오른 5967.74 마감
https://finance.naver.com/news/news_read.naver?article_id=0008889118&office_id=421&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1

[속보] 6,000선 턱밑…SK하이닉스6%·스퀘어 10%↑
https://finance.naver.com/news/news_read.naver?article_id=0001248975&office_id=215&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1

차바이오F&C, 반려동물 영양제 '펫세븐 장 케어 유산균' 출시
https://finance.naver.com/news/news_read.naver?article_id=0005507536&office_id=014&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1

코스피, 장중 '6천피' 찍고 5,960선 마감…코스닥도 올라
https://finance.naver.com/news/news_read.naver?article_id=0016021047&office_id=001&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1

코스피 5967.75(▲2.74%), 코스닥 1121.88(▲2.00%), 원·달러 환율 ..
https://finance.naver.com/news/news_read.naver?article_id=0013886989&office_id=003&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1

[코스피] 159.13포인트(2.74%) 오른 5967.75 마감
https://finance.naver.com/news/news_read.naver?article_id=0004610584&office_id=011&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1

[속보] 코스닥 1121.88…2.00% 상승 마감
https://finance.naver.com/news/news_read.naver?article_id=0001138957&office_id=417&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1

키움證 로보어드바이저 '키움모멘텀', 1년 수익률 최고수준 기록
https://finance.naver.com/news/news_read.naver?article_id=0016021042&office_id=001&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1

코스닥 22.04P 오른 1121.88 마감(2.0%↑)
https://finance.naver.com/news/news_read.naver?article_id=0005749340&office_id=277&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1

[코스닥] 22.04포인트(2.00%) 오른 1121.88 마감
https://finance.naver.com/news/news_read.naver?article_id=0004610583&office_id=011&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1

[속보]코스피, 협상 기대 속 2.74% 오른 5967.75 마감
https://finance.naver.com/news/news_read.naver?article_id=0013886984&office_id=003&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1

코스피 159.13P 오른 5967.75 마감(2.74%↑)
https://finance.naver.com/news/news_read.naver?article_id=0005749339&office_id=277&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1

[속보] 코스피 5967.74…2.74% 상승 마감
https://finance.naver.com/news/news_read.naver?article_id=0001138955&office_id=417&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1

In [277]:
soup

<!--  global include -->
<html lang="ko">
<head>
<title>Npay 증권</title>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<meta content="text/javascript" http-equiv="Content-Script-Type"/>
<meta content="text/css" http-equiv="Content-Style-Type"/>
<meta content="Npay 증권" name="apple-mobile-web-app-title">
<meta content="http://finance.naver.com/news/news_list.naver?mode=LSS2D§ion_id=101§ion_id2=258&amp;type=0" property="og:url">
<meta content="실시간 속보 : Npay 증권" property="og:title"/>
<meta content="관심종목의 실시간 주가를 가장 빠르게 확인하는 곳" property="og:description"/>
<meta content="https://ssl.pstatic.net/static/m/stock/im/2016/08/og_stock-200.png" property="og:image"/>
<meta content="article" property="og:type"/>
<meta content="" property="og:article:thumbnailUrl"/>
<meta content="Npay 증권" property="og:article:author"/>
<meta content="http://FINANCE.NAVER.COM" property="og:article:author:url"/>
<link href="https://ssl.pstatic.net/imgstock/static.pc/20260406095636/css/finance_header.css" rel="stylesheet" type="text/css"/>
<link href="https://ssl.pstatic.net/imgstock/static.pc/20260406095636/css/newstock.css" rel="stylesheet" type="text/css"/>
<link href="https://ssl.pstatic.net/imgstock/static.pc/20260406095636/css/common.css" rel="stylesheet" type="text/css"/>
<link href="https://ssl.pstatic.net/imgstock/static.pc/20260406095636/css/layout.css" rel="stylesheet" type="text/css"/>
<link href="https://ssl.pstatic.net/imgstock/static.pc/20260406095636/css/main.css" rel="stylesheet" type="text/css"/>
<link href="https://ssl.pstatic.net/imgstock/static.pc/20260406095636/css/newstock2.css" rel="stylesheet" type="text/css"/>
<link href="https://ssl.pstatic.net/imgstock/static.pc/20260406095636/css/newstock3.css" rel="stylesheet" type="text/css"/>
<link href="https://ssl.pstatic.net/imgstock/static.pc/20260406095636/css/world.css" rel="stylesheet" type="text/css"/>
<link href="https://ssl.pstatic.net/imgstock/static.pc/20260406095636/css/community.css" rel="stylesheet" type="text/css"/>
<script src="https://ssl.pstatic.net/imgstock/static.pc/20260406095636/js/jindo.min.ns.1.5.3.euckr.js" type="text/javascript"></script>
<script src="https://ssl.pstatic.net/imgstock/static.pc/20260406095636/js/release/common.js" type="text/javascript"></script>
<script src="https://ssl.pstatic.net/imgstock/static.pc/20260406095636/js/jindoComponent/jindo.Component.1.0.3.js" type="text/javascript"></script>
<script src="https://ssl.pstatic.net/imgstock/static.pc/20260406095636/js/nhn.autocomplete.stock.js" type="text/javascript"></script>
<script>
	var ieVersion = (function () {
        var version = -1;
        if (
          navigator.appName == 'Microsoft Internet Explorer' &&
          navigator.userAgent.toLowerCase().indexOf('msie') != -1 &&
          new RegExp('MSIE ([0-9]{1,}[\./0-9]{0,})').exec(navigator.userAgent) != null
        ) {
          version = parseInt(RegExp.$1);
        }
        return version;
      })();
</script>
<link href="https://ssl.pstatic.net/imgstock/favi/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
<script type="text/javascript">
    (function(){
		document.write(
				[
					'<link rel="apple-touch-icon-precomposed" href="https://ssl.pstatic.net/imgstock/favi/favicon-96x96.png"/>',
					'<link rel="apple-touch-icon-precomposed" sizes="180x180" href="https://ssl.pstatic.net/imgstock/favi/favicon-180x180.png"/>',
					'<link rel="apple-touch-icon-precomposed" sizes="192x192" href="https://ssl.pstatic.net/imgstock/favi/favicon-192x192.png"/>',
					'<link rel="icon" type="image/png" sizes="16x16" href="https://ssl.pstatic.net/imgstock/favi/favicon-16x16.png"/>',
					'<link rel="icon" type="image/png" sizes="32x32" href="https://ssl.pstatic.net/imgstock/favi/favicon-32x32.png"/>',
					'<link rel="icon" type="image/png" sizes="96x96" href="https://ssl.pstatic.net/imgstock/favi/favicon-96x96.png"/>',
					'<link rel="icon" type="image/png" sizes="192x192" href="https://ssl.pstatic.net/imgstock/favi/favicon-192x192.png"/>'
				]
			.join('\n')
		);
    })();
    </script>
</meta></meta></head>
<body onload="getGNB();">
<script type="text/javascript">







var nsc="finance.news";


var ccsrv="cc.naver.com";




	var gnb_service='finance';



var gnb_logout=document.URL; //GNB에서 로그아웃 후 redirect 될 URL
var gnb_searchbox='off'; //미니 검색창을 on 할지 off 할지. default는 off
var gnb_shortnick='off'; //닉네임 말줄임(10자)을 on할지 off 할지. default는 off.


var gnb_naverme_layer_open_callback = function(){
	   var naverLayerSize = gnbNaverMeLayer.getLayerSize();

		var me_layers = document.getElementById("me_layers");
		me_layers.width=naverLayerSize.width;
		me_layers.height=naverLayerSize.height;};

var gnb_naverme_layer_close_callback = function(){

			var me_layers = document.getElementById("me_layers");
			me_layers.width="0";
			me_layers.height="0";};
</script>
<div id="u_skip">
<a href="#menu" tabindex="1"><span>메인 메뉴로 바로가기</span></a>
<a href="#start" tabindex="2"><span>본문으로 바로가기</span></a>
</div>
<div id="header">
<div class="header_area">
<div class="header_inner">
<div class="logo_area">
<h1 class="service">
<a class="logo_link" href="https://www.naver.com/" onclick="clickcr(this, 'STA.naver', '', '', event);">
<svg fill="none" height="22" viewbox="0 0 22 22" width="22" xmlns="http://www.w3.org/2000/svg">
<path d="M22 11C22 13.1756 21.3549 15.3023 20.1462 17.1113C18.9375 18.9202 17.2195 20.3301 15.2095 21.1627C13.1995 21.9952 10.9878 22.2131 8.85401 21.7886C6.72022 21.3642 4.76021 20.3166 3.22183 18.7782C1.68345 17.2398 0.635805 15.2798 0.211368 13.146C-0.213069 11.0122 0.00476298 8.80047 0.837327 6.79048C1.66989 4.78049 3.07979 3.06253 4.88873 1.85383C6.69768 0.645137 8.82441 0 11 0C13.9174 0 16.7153 1.15893 18.7782 3.22183C20.8411 5.28473 22 8.08262 22 11ZM12.8398 5.83V11.3602L8.98976 5.83H5.83V16.1838H9.1575V10.637L13.0075 16.17H16.1783V5.83H12.8398Z" fill="#000"></path>
</svg>
<span class="blind">네이버</span>
</a>
<a class="logo_link" href="https://new-m.pay.naver.com/" onclick="clickcr(this, 'STA.pay', '', '', event);">
<svg fill="none" height="22" viewbox="0 0 37 22" width="37" xmlns="http://www.w3.org/2000/svg">
<path d="M34.4319 5.21944L31.3913 12.1478L27.9518 5.21944H25.3072L30.1783 14.8317L28.1703 19.3358H30.7384L37 5.2331L34.4319 5.21944ZM23.6171 15.9331H21.1037V14.9328C20.1894 15.7342 19.0108 16.1685 17.7953 16.1518C14.7901 16.1518 12.4379 13.692 12.4379 10.5763C12.4379 7.46057 14.7874 5.00079 17.7953 5.00079C19.0104 4.9833 20.189 5.41657 21.1037 6.21701V5.21944H23.6171V15.9331ZM21.3987 10.5899C21.3987 8.57019 19.9891 7.03694 18.1204 7.03694C16.2517 7.03694 14.842 8.57019 14.842 10.5899C14.842 12.6097 16.249 14.1429 18.1204 14.1429C19.9918 14.1429 21.3987 12.596 21.3987 10.5899ZM0.00819554 19.3358H2.63088V15.023C3.52823 15.7695 4.66309 16.1699 5.83001 16.1518C8.83516 16.1518 11.1901 13.692 11.1901 10.5763C11.1901 7.46057 8.83789 5.00079 5.83001 5.00079C4.61166 4.9789 3.42899 5.4126 2.51341 6.21701V5.21944H0L0.00819554 19.3358ZM5.51856 7.03694C7.38722 7.03694 8.79691 8.57019 8.79691 10.5899C8.79691 12.6097 7.38722 14.1429 5.51856 14.1429C3.6499 14.1429 2.24021 12.6097 2.24021 10.5899C2.24021 8.57019 3.63351 7.03694 5.51856 7.03694Z" fill="#000"></path>
</svg>
<span class="blind">페이</span>
</a>
<a class="logo_link" href="/" onclick="clickcr(this, 'STA.finance', '', '', event);">
<svg fill="none" height="22" viewbox="0 0 34 22" width="34" xmlns="http://www.w3.org/2000/svg">
<path d="M2.43006 8.88998L1.85406 6.99998C5.29206 6.31598 7.00206 5.34398 7.45206 4.31798H2.71806V2.35598H14.3641V4.31798H9.75606C9.70206 4.65998 9.61206 4.98398 9.46806 5.28998L15.2101 6.98198L14.4901 8.88998L8.02806 6.92798C6.84006 7.75598 5.00406 8.40398 2.43006 8.88998ZM0.612061 11.5V9.53798H16.4521V11.5H0.612061ZM6.53406 12.796H10.5301C13.2301 12.796 14.7961 14.128 14.7961 15.91C14.7961 17.71 13.2301 19.024 10.5301 19.024H6.53406C3.85206 19.024 2.28606 17.71 2.28606 15.91C2.28606 14.128 3.85206 12.796 6.53406 12.796ZM6.96606 17.044H10.1161C11.7901 17.044 12.4921 16.594 12.4921 15.892C12.4921 15.19 11.7901 14.776 10.1161 14.776H6.96606C5.29206 14.776 4.57206 15.19 4.57206 15.892C4.57206 16.594 5.29206 17.044 6.96606 17.044Z" fill="#000"></path>
<path d="M25.1904 13.354V11.536H29.4564V2.03198H31.7604V15.334H29.4564V13.354H25.1904ZM21.3384 10.564C20.9244 10.582 20.5464 10.582 20.1684 10.582H17.4504L17.3604 8.61998H20.3844C21.5004 8.61998 22.9584 8.56598 24.4884 8.45798C24.7224 6.99998 24.8484 5.63198 24.8664 4.62398H18.4404V2.66198H27.0984V3.56198C27.0984 5.16398 26.9724 6.76598 26.7564 8.25998L28.2684 8.09798L28.5024 10.006C26.9724 10.222 25.2264 10.384 23.5704 10.474C23.4984 11.5 23.3904 12.562 23.2644 13.714L21.0684 13.588C21.1764 12.508 21.2664 11.536 21.3384 10.564ZM22.4724 14.254V16.756H32.3724V18.844H20.1684V14.254H22.4724Z" fill="#000"></path>
</svg>
<span class="blind">증권</span>
</a>
</h1>
</div>
<div class="right_area">
<div class="search_area">
<form action="/search/search.naver" method="get" name="search" onsubmit="return delayed_submit(this)" style="margin:0; padding:0;">
<label class="blind" for="stock_items">증권 종목명·지수명 검색</label>
<input accesskey="s" autocomplete="off" class="search_input" id="stock_items" name="query" placeholder="종목명·지수명 입력" title="종목명·지수명 검색" type="text"/>
<input id="_endUrl" name="endUrl" type="hidden" value="">
<button class="search_button" onclick="clickcr(this, 'STA.search', '', '', event);" type="submit">
<svg fill="none" height="16" viewbox="0 0 16 16" width="16" xmlns="http://www.w3.org/2000/svg">
<path clip-rule="evenodd" d="M6.9999 2.59996C4.56985 2.59996 2.5999 4.56991 2.5999 6.99996C2.5999 9.43002 4.56985 11.4 6.9999 11.4C9.42996 11.4 11.3999 9.43002 11.3999 6.99996C11.3999 4.56991 9.42996 2.59996 6.9999 2.59996ZM1.3999 6.99996C1.3999 3.90717 3.90711 1.39996 6.9999 1.39996C10.0927 1.39996 12.5999 3.90717 12.5999 6.99996C12.5999 10.0928 10.0927 12.6 6.9999 12.6C3.90711 12.6 1.3999 10.0928 1.3999 6.99996Z" fill="#404048" fill-rule="evenodd"></path>
<path clip-rule="evenodd" d="M10.2421 10.2424C10.4765 10.0081 10.8564 10.0081 11.0907 10.2424L14.424 13.5758C14.6583 13.8101 14.6583 14.19 14.424 14.4243C14.1897 14.6586 13.8098 14.6586 13.5755 14.4243L10.2421 11.091C10.0078 10.8567 10.0078 10.4768 10.2421 10.2424Z" fill="#404048" fill-rule="evenodd"></path>
</svg>
<span class="blind">검색</span>
</button>
<div class="auto_area">
<span class="blind">자동완성</span>
<div id="autoFrame" style="display: none;">
<div class="wrap" id="atcmp" style="display:none;">
<div class="wrap_in">
<div class="words">
<ul class="_resultBox">
<li>
<a class="_au_real_list" href="#" onclick="clickcr(this, 'AUT.list', '', '', event); return false;">
<span class="num _au_real_list">@code@</span>
<span class="_au_real_list">@txt@</span>
<span class="type _au_real_list">@market@</span>
</a>
<div class="_au_full" style="display:none">@full_txt@</div>
<div class="_au_code" style="display:none">@in_code@</div>
<div class="_au_name" style="display:none">@in_name@</div>
<div class="_au_link" style="display:none">@in_link@</div>
<div class="_au_market" style="display:none">@in_market@</div>
</li>
</ul>
<div class="search_notice">
<p class="text">
												공모주와 해외 종목은 모바일 페이지로 이동합니다.
											</p>
</div>
</div>
</div>
<!-- 현재 자동완성 기능을 사용하고 계십니다 -->
<div class="wrap" id="atcmpIng" style="display:none;">
<div class="wrap_in">
<div class="words">
<p class="msg">
												현재 자동완성 기능을 사용하고 계십니다.
											</p>
</div>
</div>
</div>
<!--// 현재 자동완성 기능을 사용하고 계십니다 -->
<!-- 자동완성 기능이 활성화 -->
<div class="wrap" id="atcmpStart" style="display:none;">
<div class="wrap_in">
<div class="words">
<p class="msg">
												자동완성 기능이 활성화되었습니다.
											</p>
</div>
</div>
</div>
</div>
</div>
</div>
</input></form>
</div>
<div class="gnb_area">
<div id="gnb">
<script charset="EUC-KR" type="text/javascript">
							var gnb_service = "finance";
							var gnb_template = location.protocol === "http:" ? "gnb_quirks_euckr" : "gnb_utf8" ;
							var gnb_logout=encodeURIComponent(location.href);
							var gnb_brightness = 1;
							var gnb_one_naver = 0;
						</script>
<script charset="utf-8" src="https://ssl.pstatic.net/static.gn/templates/gnb_utf8.nhn?20260414" type="text/javascript">
</script>
</div>
</div>
</div>
</div>
</div>
<div class="lnb_area">
<div class="lnb_inner">
<div id="menu">
<ul class="menu">
<li class="m1 first"><a href="/" onclick="clickcr(this, 'LNB.home', '', '', event);"><span class="tx">증권 홈</span></a></li>
<li class="m2"><a href="/sise/" onclick="clickcr(this, 'LNB.sise', '', '', event);"><span class="tx">국내증시</span></a></li>
<li class="m3"><a href="/world/" onclick="clickcr(this, 'LNB.world', '', '', event);"><span class="tx">해외증시</span></a></li>
<li class="m4"><a href="/marketindex/" onclick="clickcr(this, 'LNB.market', '', '', event);"><span class="tx">시장지표</span></a></li>
<li class="m6"><a href="/research/" onclick="clickcr(this, 'LNB.research', '', '', event);"><span class="tx">리서치</span></a></li>
<li class="m7 on"><a href="/news/"><span class="tx">뉴스</span><span class="blind">선택됨</span></a></li>
<li class="m8"><a href="/mystock/" onclick="clickcr(this, 'LNB.mystock', '', '', event);"><span class="tx">MY</span></a></li>
</ul>
<!-- 새로운 증권보기 버튼 -->
<div class="area_stock_button">
<a class="link_new" href="https://stock.naver.com">
<span class="icon_refresh"></span>
						새로운 증권 보기
						<span class="icon_new">
<span class="blind">NEW</span>
</span>
</a>
<span class="tooltip">
						더 편리해진 증권을 만나보세요
						<span class="icon_arrow"></span>
</span>
</div>
<!-- //새로운 증권보기 버튼 -->
</div>
</div>
</div>
<script type="text/JavaScript">
		/* lcs 집계 */
        ;(function(){
            var eventType = "onpageshow" in window ? "pageshow" : "load";
            jindo.$Fn(function(){
                lcs_do();
            }).attach(window, eventType);
        })();

		/* 검색 자동완성 [ 인자1 : 검색input의 ID, 인자2 : iframe 태그 ID ]   */
		// AutoComplete 생성
		var acDomain = "ac.stock.naver.com";
		if (location.hostname.indexOf("staging-") > -1) {
			acDomain = "staging-" + acDomain;
		} else if (location.hostname.indexOf("test-") > -1) {
			acDomain = "test-" + acDomain;
		} else if (location.hostname.indexOf("dev-") > -1 || location.hostname.indexOf("localhost") > -1 || location.hostname.indexOf("local-") > -1) {
			acDomain = "dev-" + acDomain;
		}

        var acUrl = "https://" + acDomain + "/ac";

		smartSearch = new nhn.Autocomplete(
			// InputManager 생성
			new nhn.AcInputManager(jindo.$("stock_items")),
			// DataManager 생성
			new nhn.AcDataManager(acUrl, "xhr", "get", {}),
			// ViewManager 생성
			new nhn.AcStockViewManager(jindo.$("autoFrame"), jindo.$("nautocomplete"), {
                                        strMax: 200,
                                        listMax: [7, 2, 2],
                                        aRedirectUrl: [
										"https://" + window.location.hostname,
                            			"https://finance.naver.com",
                            			"https://finance.naver.com"],
										mobileUrl: "https://m.stock.naver.com"}),
			// Autocomplete Option
            {formId:"search", cookieDomain:location.hostname, cookieName:"NaverCommonStock_disable"});

			smartSearch.attach({
	            onFocus: function () {
	                var weInput = jindo.$Element('stock_items');
	                if (weInput && weInput.hasClass("snb_default")) {
	                        weInput.text("");
	                        weInput.removeClass('snb_default');
	                }
	            }
	        });

		/* 통합검색  start ----->  */
		var sSearchHintText = '종목명·지수명·환율명·원자재명 입력';
		function itegrationSearch() {
			var query = jindo.$('stock_items').value;

			if ( query == ''  || encodeURIComponent(query) == encodeURIComponent(sSearchHintText))
			{
				alert ( '검색어를 입력해 주세요.' );
				return;
			}

            var url = "https://search.naver.com/search.naver?sm=sta_hty.finance&where=nexearch&ie=UTF8&query=" + encodeURIComponent(query);
            window.open(url, "_blank");

			return false;
		}

		function delayed_submit(object) {
			if (navigator.userAgent.indexOf('MSIE') == -1) {
				window.setTimeout(function() {stock_search(object)}, 300);
			} else {
				stock_search(object);
			}
			return false;
		}

		function stock_search (object) {
			// endUrl check
			if (object.endUrl.value) {
				if (object.endUrl.value.startsWith("https://m.stock.naver.com")) {
					// 검색정보 초기화
					var _endUrl = object.endUrl.value;
					object.query.value = "";
					object.endUrl.value = "";
					document.getElementById("atcmp").style.display="none";
					window.open(_endUrl, "_blank");
				} else {
					location.href = object.endUrl.value;
				}

				return;
			}

			// query check
			query = object.query.value.replace(/^\s*/,'').replace(/\s*$/,'');	// trim
			object.query.value=query;

			if ( query == '' || query == sSearchHintText.replace(/^\s*/,'').replace(/\s*$/,''))
			{
				alert ( '검색어를 입력해 주세요.' );
				return;
			}
			else {
				object.submit();
			}
		}
		/* <---------- 통합검색  end */

		function popup()
		{
			win = window.open('/template/group_limit_pop.jsp','finan_popup','width=569 height=278 scrollbars=no status=no');
			win.focus();
		}
	</script>
<iframe frameborder="0" height="0" id="me_layers" name="test" scrolling="no" style="display:block;top: 22px; right: 209px; position: absolute; z-index: 15;" title="네이버미 영역" width="0"></iframe>
</div>
<div id="wrap">
<!-- //  global include -->
<div class="_replaceNewsLink" id="newarea">
<!-- leftmenu -->
<div class="snb snb2 snb3 snb_news">
<h2 class="h_news"><a href="/news/" onclick="clickcr(this, 'new.news', '', '', event)"><span class="blind">뉴스</span></a></h2>
<ul class="nav1">
<li class="frst"><a href="/news/news_list.naver?mode=LSS2D§ion_id=101§ion_id2=258" onclick="clickcr(this, 'new.real', '', '', event)"><strong class="other2 lst_news"><span class="blind">실시간속보</span></strong></a></li>
<li><a href="/news/mainnews.naver" onclick="clickcr(this, 'new.main', '', '', event)"><strong class="other2 lst_news2"><span class="blind">주요뉴스</span></strong></a></li>
<li class="another"><strong class="news_focus"><span class="blind">뉴스 포커스</span></strong>
<ul class="sub">
<li class="lst3_1"><a class="off" href="/news/news_list.naver?mode=LSS3D§ion_id=101§ion_id2=258§ion_id3=401" onclick="clickcr(this, 'new.fore', '', '', event)"><span class="blind">시황·전망</span></a></li>
<li class="lst3_2"><a class="off" href="/news/news_list.naver?mode=LSS3D§ion_id=101§ion_id2=258§ion_id3=402" onclick="clickcr(this, 'new.firm', '', '', event)"><span class="blind">기업·종목분석</span></a></li>
<li class="lst3_3"><a class="off" href="/news/news_list.naver?mode=LSS3D§ion_id=101§ion_id2=258§ion_id3=403" onclick="clickcr(this, 'new.aboard', '', '', event)"><span class="blind">해외증시</span></a></li>
<li class="lst3_4"><a class="off" href="/news/news_list.naver?mode=LSS3D§ion_id=101§ion_id2=258§ion_id3=404" onclick="clickcr(this, 'new.bond', '', '', event)"><span class="blind">채권·선물</span></a></li>
<li class="lst3_5"><a class="off" href="/news/news_list.naver?mode=LSS3D§ion_id=101§ion_id2=258§ion_id3=406" onclick="clickcr(this, 'new.memo', '', '', event)"><span class="blind">공시·메모</span></a></li>
<li class="lst3_6"><a class="off" href="/news/news_list.naver?mode=LSS3D§ion_id=101§ion_id2=258§ion_id3=429" onclick="clickcr(this, 'new.currency', '', '', event)"><span class="blind">환율</span></a></li>
</ul>
</li>
<li><a href="/news/news_list.naver?mode=RANK" onclick="clickcr(this, 'new.best', '', '', event)"><strong class="other2 lst_news5"><span class="blind">많이 본 뉴스</span></strong></a></li>
<li><a href="/news/news_list.naver?mode=LSTD§ion_id=101§ion_id2=258&amp;type=1" onclick="clickcr(this, 'new.photo', '', '', event)"><strong class="other2 lst_news6"><span class="blind">포토뉴스</span></strong></a></li>
<li><a href="/news/news_list.naver?mode=TV§ion_id=tv" onclick="clickcr(this, 'new.tv', '', '', event)"><strong class="other2 lst_news7"><span class="blind">TV뉴스</span></strong></a></li>

In [278]:
articleSummary_list = soup.select('.articleSummary')

In [279]:
articleSummary_list[0]

<dd class="articleSummary">


										[이데일리 김경은 기자]



								<span class="press">이데일리</span>
<span class="bar">|</span>
<span class="wdate">2026-04-14 15:41</span>
</dd>

In [280]:
for i in articleSummary_list:
    press_tag = i.select_one('.press')
    press = press_tag.get_text(strip=True)
    print(press)

이데일리
서울경제
뉴스1
한국경제
연합뉴스TV
뉴스1
뉴스1
뉴스1
한국경제TV
파이낸셜뉴스
연합뉴스
뉴시스
서울경제
동행미디어 시대
연합뉴스
아시아경제
서울경제
뉴시스
아시아경제
동행미디어 시대

In [281]:
for i, item in enumerate(articlesubject_list):
    a_tag = item.select_one('a')
    title = a_tag.get_text(strip=True)
    link = 'https://finance.naver.com'+a_tag.get('href', '')
    press = articleSummary_list[i].select_one('.press').get_text(strip=True)
    dummy_dict = {'제목':title, 'URL':link, '언론사':press, '페이지':page}
    print(dummy_dict)

{'제목': '[속보]코스피, 2.74% 오른 5967.75...코스닥, 2.0% 상승 마감', 'URL': 'https://finance.naver.com/news/news_read.naver?article_id=0006257135&office_id=018&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1', '언론사': '이데일리', '페이지': 1}
{'제목': '위험선호 확산 vs 결제수요…환율 1480원대 공방 [김혜란의 FX]', 'URL': 'https://finance.naver.com/news/news_read.naver?article_id=0004610586&office_id=011&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1', '언론사': '서울경제', '페이지': 1}
{'제목': '코스피,  2.74% 상승한 5967.75 마감…코스닥 2.00%↑(2보)', 'URL': 'https://finance.naver.com/news/news_read.naver?article_id=0008889145&office_id=421&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1', '언론사': '뉴스1', '페이지': 1}
{'제목': "외국인 현·선물 2.7조 순매수에…'육천피' 턱밑까지", 'URL': 'https://finance.naver.com/news/news_read.naver?article_id=0005274805&office_id=015&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1', '언론사': '한국경제', '페이지': 1}
{'제목': '코스피, 2.74% 오른 5,967.75 마감…코스닥도 2%↑', 'URL': 'https://finance.naver.com/news/news_read.naver?article_id=0000854953&office_id=422&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1', '언론사': '연합뉴스TV', '페이지': 1}
{'제목': '[달러·원] 환율 8.1원 내 1481.2원 마감', 'URL': 'https://finance.naver.com/news/news_read.naver?article_id=0008889132&office_id=421&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1', '언론사': '뉴스1', '페이지': 1}
{'제목': '[코스닥] 22.04p(2.00%) 오른 1121.88 마감', 'URL': 'https://finance.naver.com/news/news_read.naver?article_id=0008889128&office_id=421&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1', '언론사': '뉴스1', '페이지': 1}
{'제목': '[코스피] 159.12p(2.74%) 오른 5967.74 마감', 'URL': 'https://finance.naver.com/news/news_read.naver?article_id=0008889118&office_id=421&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1', '언론사': '뉴스1', '페이지': 1}
{'제목': '[속보] 6,000선 턱밑…SK하이닉스6%·스퀘어 10%↑', 'URL': 'https://finance.naver.com/news/news_read.naver?article_id=0001248975&office_id=215&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1', '언론사': '한국경제TV', '페이지': 1}
{'제목': "차바이오F&C, 반려동물 영양제 '펫세븐 장 케어 유산균' 출시", 'URL': 'https://finance.naver.com/news/news_read.naver?article_id=0005507536&office_id=014&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1', '언론사': '파이낸셜뉴스', '페이지': 1}
{'제목': "코스피, 장중 '6천피' 찍고 5,960선 마감…코스닥도 올라", 'URL': 'https://finance.naver.com/news/news_read.naver?article_id=0016021047&office_id=001&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1', '언론사': '연합뉴스', '페이지': 1}
{'제목': '코스피 5967.75(▲2.74%), 코스닥 1121.88(▲2.00%), 원·달러 환율 ..', 'URL': 'https://finance.naver.com/news/news_read.naver?article_id=0013886989&office_id=003&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1', '언론사': '뉴시스', '페이지': 1}
{'제목': '[코스피] 159.13포인트(2.74%) 오른 5967.75 마감', 'URL': 'https://finance.naver.com/news/news_read.naver?article_id=0004610584&office_id=011&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1', '언론사': '서울경제', '페이지': 1}
{'제목': '[속보] 코스닥 1121.88…2.00% 상승 마감', 'URL': 'https://finance.naver.com/news/news_read.naver?article_id=0001138957&office_id=417&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1', '언론사': '동행미디어 시대', '페이지': 1}
{'제목': "키움證 로보어드바이저 '키움모멘텀', 1년 수익률 최고수준 기록", 'URL': 'https://finance.naver.com/news/news_read.naver?article_id=0016021042&office_id=001&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1', '언론사': '연합뉴스', '페이지': 1}
{'제목': '코스닥 22.04P 오른 1121.88 마감(2.0%↑)', 'URL': 'https://finance.naver.com/news/news_read.naver?article_id=0005749340&office_id=277&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1', '언론사': '아시아경제', '페이지': 1}
{'제목': '[코스닥] 22.04포인트(2.00%) 오른 1121.88 마감', 'URL': 'https://finance.naver.com/news/news_read.naver?article_id=0004610583&office_id=011&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1', '언론사': '서울경제', '페이지': 1}
{'제목': '[속보]코스피, 협상 기대 속 2.74% 오른 5967.75 마감', 'URL': 'https://finance.naver.com/news/news_read.naver?article_id=0013886984&office_id=003&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1', '언론사': '뉴시스', '페이지': 1}
{'제목': '코스피 159.13P 오른 5967.75 마감(2.74%↑)', 'URL': 'https://finance.naver.com/news/news_read.naver?article_id=0005749339&office_id=277&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1', '언론사': '아시아경제', '페이지': 1}
{'제목': '[속보] 코스피 5967.74…2.74% 상승 마감', 'URL': 'https://finance.naver.com/news/news_read.naver?article_id=0001138955&office_id=417&mode=LSS2D&type=0§ion_id=101§ion_id2=258§ion_id3=&date=20260414&page=1', '언론사': '동행미디어 시대', '페이지': 1}

In [289]:
def parse_page(page):
    base_url = 'https://finance.naver.com/news/news_list.naver'
    base_params = {'mode':'LSS2D', 'section_id':'101', 'section_id2':'258'}
    params={**base_params, 'page':page}
    response = requests.get(base_url, params=params)
    soup = bs(response.text, 'html.parser')

    a_sub_list = soup.select('.articleSubject')
    a_smm_list = soup.select('.articleSummary')
    articles = []

    for i, item in enumerate(a_sub_list):
        a_tag = item.select_one('a')
        title = a_tag.get_text(strip=True)
        href = 'https://finance.naver.com'+a_tag.get('herf', '')
        press = a_smm_list[i].select_one('.press').get_text(strip=True)
        dummy_dict = {'제목':title, 'URL':href, '언론사':press, '페이지':page}
        articles.append(dummy_dict)
    return articles

In [290]:
articles = parse_page(2)

In [291]:
articles

[{'제목': '코스피, 장중 6000선 터치하고 5900선 마감',
  'URL': 'https://finance.naver.com',
  '언론사': '뉴시스',
  '페이지': 2},
 {'제목': '코스피 상승, 원·달러 환율 하락 마감',
  'URL': 'https://finance.naver.com',
  '언론사': '뉴스1',
  '페이지': 2},
 {'제목': '코스피, 6000선 턱밑에서 장 마감',
  'URL': 'https://finance.naver.com',
  '언론사': '뉴스1',
  '페이지': 2},
 {'제목': "9일간 '147조' 터졌다…주가 급등에 개미들 환호한 종목",
  'URL': 'https://finance.naver.com',
  '언론사': '한국경제',
  '페이지': 2},
 {'제목': '코스피·코스닥 상승, 원·달러 환율 하락 마감',
  'URL': 'https://finance.naver.com',
  '언론사': '뉴스1',
  '페이지': 2},
 {'제목': "협상 기대감에 '육천피' 눈앞…외국인·기관 '쌍끌이' 매수",
  'URL': 'https://finance.naver.com',
  '언론사': '연합뉴스TV',
  '페이지': 2},
 {'제목': "중동 종전 기대감에 '증시 상승·환율 하락'",
  'URL': 'https://finance.naver.com',
  '언론사': '뉴스1',
  '페이지': 2},
 {'제목': "코스피, 장중 '6000피' 재돌파 후 5960선 마감",
  'URL': 'https://finance.naver.com',
  '언론사': '뉴스1',
  '페이지': 2},
 {'제목': '코스피·코스닥 동반 상승',
  'URL': 'https://finance.naver.com',
  '언론사': '뉴스1',
  '페이지': 2},
 {'제목': '상승 마감한 국내 증시',
  'URL': 'https://finance.naver.com',
  '언론사': '뉴시스',
  '페이지': 2},
 {'제목': '코스피, 장중 6000선 터치하고 5900선 마감',
  'URL': 'https://finance.naver.com',
  '언론사': '뉴시스',
  '페이지': 2},
 {'제목': '코스피 5900선 마감',
  'URL': 'https://finance.naver.com',
  '언론사': '뉴시스',
  '페이지': 2},
 {'제목': '코스피, 장중 6000선 터치하고 5900선 마감',
  'URL': 'https://finance.naver.com',
  '언론사': '뉴시스',
  '페이지': 2},
 {'제목': '코스피 상승 마감, 원·달러 환율 하락',
  'URL': 'https://finance.naver.com',
  '언론사': '뉴시스',
  '페이지': 2},
 {'제목': '코스피 5900선 마감',
  'URL': 'https://finance.naver.com',
  '언론사': '뉴시스',
  '페이지': 2},
 {'제목': '상승 마감한 국내 증시',
  'URL': 'https://finance.naver.com',
  '언론사': '뉴시스',
  '페이지': 2},
 {'제목': '코스피, 장중 6000선 터치하고 5900선 마감',
  'URL': 'https://finance.naver.com',
  '언론사': '뉴시스',
  '페이지': 2},
 {'제목': '코스피, 장중 6000선 터치하고 5900선 마감',
  'URL': 'https://finance.naver.com',
  '언론사': '뉴시스',
  '페이지': 2},
 {'제목': '상승 마감한 국내 증시',
  'URL': 'https://finance.naver.com',
  '언론사': '뉴시스',
  '페이지': 2},
 {'제목': '에이전트AI, 95% 감자 완료…자본금 399억→19억 ‘급감’',
  'URL': 'https://finance.naver.com',
  '언론사': '디지털데일리',
  '페이지': 2}]

In [296]:
import time

In [306]:
def finance_news(max_pages=3, delay=1.0):
    all_articles = []
    for page in range(1, max_pages+1):
        print(f"{page} / {max_pages}번째 페이지 수집 중...")
        try:
            articles = parse_page(page)
            all_articles.extend(articles)
        except Exception as e:
            print(e)
        if page < max_pages:
            time.sleep(delay)
    df = pd.DataFrame(all_articles)
    print(f"총 {len(df)} 건 수집 완료\n")
    return df

In [307]:
finance_news(3)

1 / 3번째 페이지 수집 중...
2 / 3번째 페이지 수집 중...
3 / 3번째 페이지 수집 중...
총 60 건 수집 완료

,제목,URL,언론사,페이지
0,"하나운용, ETF 보수 인상에도 “최저” 홍보…당국 기조 ‘역행’[only 이데일리]",https://finance.naver.com,이데일리,1
1,"NH증권, '예탁자산 300억' 패밀리오피스 세미나 개최",https://finance.naver.com,뉴시스,1
2,[뉴스1PICK]코스피 장중 6000선 터치 후 5967선 마감…반도체주 강세 영향,https://finance.naver.com,뉴스1,1
3,"[특징주] LS일렉트릭, 대규모 전력 인프라 수주에 52주 신고가(종합)",https://finance.naver.com,연합뉴스,1
4,"큐라티스, 9대1 주식병합 감자 결정",https://finance.naver.com,이데일리,1
5,[단독] ‘K-푸드’ 본촌치킨 매각 급물살…본입찰 착수,https://finance.naver.com,헤럴드경제,1
6,"""이익 1000조 시대""…코스피 7500선 '현실화 구간' 진입",https://finance.naver.com,파이낸셜뉴스,1
7,"'HBM 12단도 넘본다'…中반도체 공룡, 'K-초격차' 흔들까",https://finance.naver.com,비즈워치,1
8,AI 인프라 투자 기대 재점화…LS일렉트릭 신고가 터치[핫종목](종합),https://finance.naver.com,뉴스1,1
9,"에스바이오메딕스, 400억 규모 자금 조달",https://finance.naver.com,매일경제,1
10,“다음은 누구 차례?”…주가 100만원 고지 노리는 ‘예비 황제주’,https://finance.naver.com,매일경제,1
11,"코스맥스엔비티, 주주 4명 장부열람 가처분 일부 인용",https://finance.naver.com,이데일리,1
12,새벽 전기료 인상 부담에…500여개사 시간대별 요금제 유예 신청,https://finance.naver.com,이데일리,1
13,"""이란 전쟁에도 美 기업 1분기 실적 호조 전망""",https://finance.naver.com,아시아경제,1
14,위험 선호 심리 회복·유가 하락…달러·원 환율 1480원대 마감(종합),https://finance.naver.com,뉴스1,1
15,"""수수료 면제·금리 우대""… 우리은행, 수출 기업에 3조 원 금융지원",https://finance.naver.com,한국일보,1
16,"에스바이오메딕스, 177억원 규모 제3자배정 유상증자 결정",https://finance.naver.com,이데일리,1
17,"테크윙, 마이크론메모리말레이시아와 228억원 규모 반도체 검사장비 공급 계약",https://finance.naver.com,이데일리,1
18,[특징주] 호르무즈 해협 '역봉쇄'에 알루미늄 관련주 혼조 마감(종합),https://finance.naver.com,연합뉴스,1
19,"""주식 비중 절반까지""...채권혼합형 ETF 손보는 운용사들",https://finance.naver.com,파이낸셜뉴스,1
20,"""주식 비중 절반까지""...채권혼합형 ETF 손보는 운용사들",https://finance.naver.com,파이낸셜뉴스,2
21,"코스콤, 교보증권과 토큰증권 플랫폼 사업 추진 MOU",https://finance.naver.com,파이낸셜뉴스,2
22,"코스피, 협상 기대감에 장중 '6천피' 재돌파…5,960선 마감(종합)",https://finance.naver.com,연합뉴스,2
23,키움 로보어드바이저 1위?…수익률 143%인데 연환산은 11% 그쳐,https://finance.naver.com,연합뉴스TV,2
24,“300억 자산가 모였다”…NH투자증권 ‘패밀리오피스 초청 세미나’ 개최,https://finance.naver.com,디지털데일리,2
25,"SK하이닉스 1,103,000원 신고가…전쟁중 '육천피' 탈환 견인[핫종목](종합)",https://finance.naver.com,뉴스1,2
26,상승 마감한 코스피,https://finance.naver.com,뉴스1,2
27,변동장세에 숨죽이던 개미 기지개…코스피 '빚투' 사상 최대,https://finance.naver.com,파이낸셜뉴스,2
28,"JP모건, 신성이엔지 주요주주 등극…클린룸 회복·신사업 기대 반영",https://finance.naver.com,이데일리,2
29,"코스피, 상승폭 일부 줄이며 5967.75 마감...코스닥, 1100선 회복[fn마...",https://finance.naver.com,파이낸셜뉴스,2
30,"코스피, 협상 기대 속 2% 강세 마감…장중 6000선 돌파(종합)",https://finance.naver.com,뉴시스,2
31,"日증시, 美·이란 협상 기대에 상승 마감…닛케이지수 2.43%↑",https://finance.naver.com,뉴시스,2
32,"코스피, 기관·외국인 쌍끌이 매수에 2%대 강세…5960선 마감",https://finance.naver.com,아시아경제,2
33,"‘협상 기대감’ 코스피, 코스닥 동반 상승 마감",https://finance.naver.com,서울경제,2
34,‘육천피’ 목전에 둔 코스피,https://finance.naver.com,서울경제,2
35,종전 기대감에 6000 목전에 마감한 코스피,https://finance.naver.com,서울경제,2
36,코스피 '육천피' 돌파 후 상승폭 축소…5990선 마감[시황종합],https://finance.naver.com,뉴스1,2
37,"110만닉스 시대 개막…코스피, 협상 기대에 6000선 턱밑 [시황]",https://finance.naver.com,데일리안,2
38,"웹젠, 인디 전략 RPG '메모리스' 28일 정식 출시",https://finance.naver.com,아시아경제,2
39,"코스피, 간만에 ‘육천피’ 찍고 하락 마감…실적 기대감에 ‘110만닉스’ 복귀 [투...",https://finance.naver.com,헤럴드경제,2
40,"코스피, 장중 6000선 터치하고 5900선 마감",https://finance.naver.com,뉴시스,3
41,"코스피 상승, 원·달러 환율 하락 마감",https://finance.naver.com,뉴스1,3
42,"코스피, 6000선 턱밑에서 장 마감",https://finance.naver.com,뉴스1,3
43,9일간 '147조' 터졌다…주가 급등에 개미들 환호한 종목,https://finance.naver.com,한국경제,3
44,"코스피·코스닥 상승, 원·달러 환율 하락 마감",https://finance.naver.com,뉴스1,3
45,협상 기대감에 '육천피' 눈앞…외국인·기관 '쌍끌이' 매수,https://finance.naver.com,연합뉴스TV,3
46,중동 종전 기대감에 '증시 상승·환율 하락',https://finance.naver.com,뉴스1,3
47,"코스피, 장중 '6000피' 재돌파 후 5960선 마감",https://finance.naver.com,뉴스1,3
48,코스피·코스닥 동반 상승,https://finance.naver.com,뉴스1,3
49,상승 마감한 국내 증시,https://finance.naver.com,뉴시스,3
50,"코스피, 장중 6000선 터치하고 5900선 마감",https://finance.naver.com,뉴시스,3
51,코스피 5900선 마감,https://finance.naver.com,뉴시스,3
52,"코스피, 장중 6000선 터치하고 5900선 마감",https://finance.naver.com,뉴시스,3
53,"코스피 상승 마감, 원·달러 환율 하락",https://finance.naver.com,뉴시스,3
54,코스피 5900선 마감,https://finance.naver.com,뉴시스,3
55,상승 마감한 국내 증시,https://finance.naver.com,뉴시스,3
56,"코스피, 장중 6000선 터치하고 5900선 마감",https://finance.naver.com,뉴시스,3
57,"코스피, 장중 6000선 터치하고 5900선 마감",https://finance.naver.com,뉴시스,3
58,상승 마감한 국내 증시,https://finance.naver.com,뉴시스,3
59,"에이전트AI, 95% 감자 완료…자본금 399억→19억 ‘급감’",https://finance.naver.com,디지털데일리,3

In [303]:
finance_news(10)

총 200 건 수집 완료

,제목,URL,언론사,페이지
0,"가상자산거래, 업비트만 위험관리 ‘합격’",https://finance.naver.com,매일경제,1
1,"하나운용, ETF 보수 인상에도 “최저” 홍보…당국 기조 ‘역행’[only 이데일리]",https://finance.naver.com,이데일리,1
2,"NH증권, '예탁자산 300억' 패밀리오피스 세미나 개최",https://finance.naver.com,뉴시스,1
3,[뉴스1PICK]코스피 장중 6000선 터치 후 5967선 마감…반도체주 강세 영향,https://finance.naver.com,뉴스1,1
4,"[특징주] LS일렉트릭, 대규모 전력 인프라 수주에 52주 신고가(종합)",https://finance.naver.com,연합뉴스,1
...,...,...,...,...
195,"최영훈 채비 대표 ""전기차 급속충전 호황 타고 실적 개선 이뤄내겠다""",https://finance.naver.com,동행미디어 시대,10
196,'3高' 불청객이 왔다...진짜 관심주는 따로 있다는데 [마켓딥다이브],https://finance.naver.com,한국경제TV,10
197,스페이스X 상장 수혜...TIGER 미국우주테크 ETF 상장,https://finance.naver.com,머니투데이,10
198,"키움증권, LG·런던거래소와 AI 기반 투자서비스 '맞손'",https://finance.naver.com,연합뉴스TV,10
199,"리가켐바이오, 신규 항체-약물접합체 1·2상 계획서 제출",https://finance.naver.com,비즈워치,10

# contentarea_left > ul > li.newsList.top > dl > dd:nth-child(2)

//*[@id="contentarea_left"]/ul/li[1]/dl/dd[1]

/html/body/div[3]/div[1]/div[2]/div[1]/ul/li[1]/dl/dd[1]

In [309]:
url = 'https://www.chicagomag.com/chicago-magazine/january-2023/our-30-favorite-things-to-eat-right-now/'

In [310]:
resp = requests.get(url)

In [312]:
resp
# 403 접근거부 내일 하는법 알려줌