In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
titanic = sns.load_dataset('titanic')

In [ ]:
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [ ]:
titanic.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [ ]:
df = titanic.loc[:, ['age', 'fare']]

In [ ]:
df

      age     fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [ ]:
ser = df.iloc[:, 0]

In [ ]:
ser

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [ ]:
df = df.iloc[:10]

In [ ]:
df.rename(columns={'age':'나이'})

     나이     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
7   2.0  21.0750
8  27.0  11.1333
9  14.0  30.0708

In [ ]:
df.index=(list('abcdefghij'))

In [ ]:
df

    age     fare
a  22.0   7.2500
b  38.0  71.2833
c  26.0   7.9250
d  35.0  53.1000
e  35.0   8.0500
f   NaN   8.4583
g  54.0  51.8625
h   2.0  21.0750
i  27.0  11.1333
j  14.0  30.0708

In [ ]:
df.reset_index(drop=True)

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
7   2.0  21.0750
8  27.0  11.1333
9  14.0  30.0708

In [ ]:
df.age[5] = 35.0

/tmp/ipykernel_911/48931834.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df.age[5] = 35.0
/tmp/ipykernel_911/48931834.py:1: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  df.age[5] = 35.0
/tmp/ipykernel_911/48931834.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.age[5] = 35.0

In [ ]:
df.drop('fare', axis=1)

    age
a  22.0
b  38.0
c  26.0
d  35.0
e  35.0
f  35.0
g  54.0
h   2.0
i  27.0
j  14.0

In [ ]:
num_age = 22
df.query('age > @num_age')

    age     fare
b  38.0  71.2833
c  26.0   7.9250
d  35.0  53.1000
e  35.0   8.0500
f  35.0   8.4583
g  54.0  51.8625
i  27.0  11.1333

In [ ]:
df.to_csv('test.csv', index=False)

In [ ]:
cat test.csv

age,fare
22.0,7.25
38.0,71.2833
26.0,7.925
35.0,53.1
35.0,8.05
35.0,8.4583
54.0,51.8625
2.0,21.075
27.0,11.1333
14.0,30.0708

In [ ]:
df = pd.read_csv('test.csv', skiprows=[1, 2, 4], header=[0])

In [ ]:
df

    age     fare
0  26.0   7.9250
1  35.0   8.0500
2  35.0   8.4583
3  54.0  51.8625
4   2.0  21.0750
5  27.0  11.1333
6  14.0  30.0708

In [ ]:
sort_df = df.sort_values(by='age', ascending=False)

In [ ]:
sort_df

    age     fare
3  54.0  51.8625
2  35.0   8.4583
1  35.0   8.0500
5  27.0  11.1333
0  26.0   7.9250
6  14.0  30.0708
4   2.0  21.0750

In [ ]:
sort_df.sort_index()

    age     fare
0  26.0   7.9250
1  35.0   8.0500
2  35.0   8.4583
3  54.0  51.8625
4   2.0  21.0750
5  27.0  11.1333
6  14.0  30.0708

In [ ]:
df = sns.load_dataset('titanic')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [ ]:
df.sex.value_counts(dropna=False)

sex
male      577
female    314
Name: count, dtype: int64

In [ ]:
df.head().notnull()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True

In [ ]:
df.deck.head()

0    NaN
1      C
2    NaN
3      C
4    NaN
Name: deck, dtype: category
Categories (7, object): ['A', 'B', 'C', 'D', 'E', 'F', 'G']

In [ ]:
df.deck.value_counts()

deck
C    59
B    47
D    33
E    32
A    15
F    13
G     4
Name: count, dtype: int64

In [ ]:
df.isnull()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
887,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False
889,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False

In [ ]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
df_thresh = df.dropna(axis=1, thresh=400)

In [ ]:
df_thresh.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'embark_town', 'alive',
       'alone'],
      dtype='object')

In [ ]:
df_thresh

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,Queenstown,no,True

In [ ]:
df.count()

survived       891
pclass         891
sex            891
age            714
sibsp          891
parch          891
fare           891
embarked       889
class          891
who            891
adult_male     891
deck           203
embark_town    889
alive          891
alone          891
dtype: int64

In [ ]:
df_age_deck = df.dropna(subset=['age', 'deck'], how='all', axis=0)

In [ ]:
len(df_age_deck)

733

In [ ]:
df.age.isnull().sum()

np.int64(177)

In [ ]:
df['age'] = df['age'].fillna(df['age'].mean())

In [ ]:
df.age.isnull().sum()

np.int64(0)

In [ ]:
df['embark_town'].value_counts().idxmax()

'Southampton'

In [ ]:
df_et = df['embark_town'].value_counts()

In [ ]:
type(df_et)

pandas.core.series.Series

In [ ]:
most_freq = df_et.idxmax()

In [ ]:
most_freq

'Southampton'

In [ ]:
df['embark_town'].fillna(most_freq) # nan 값을 'Southampton'으로 대체

0      Southampton
1        Cherbourg
2      Southampton
3      Southampton
4      Southampton
          ...
886    Southampton
887    Southampton
888    Southampton
889      Cherbourg
890     Queenstown
Name: embark_town, Length: 891, dtype: object

In [ ]:
df_mode = df.embark_town.mode()[0]

In [ ]:
df_mode

'Southampton'

In [ ]:
df['embark_town'].ffill() # 앞에 있는 값으로 nan을 채움

0      Southampton
1        Cherbourg
2      Southampton
3      Southampton
4      Southampton
          ...
886    Southampton
887    Southampton
888    Southampton
889      Cherbourg
890     Queenstown
Name: embark_town, Length: 891, dtype: object

In [ ]:
df['embark_town'][825:831]

825     Queenstown
826    Southampton
827      Cherbourg
828     Queenstown
829            NaN
830      Cherbourg
Name: embark_town, dtype: object

In [ ]:
df['embark_town'].ffill()[825:831]

825     Queenstown
826    Southampton
827      Cherbourg
828     Queenstown
829     Queenstown
830      Cherbourg
Name: embark_town, dtype: object

In [ ]:
df['embark_town'].bfill()[825:831] # 뒤의 값으로 nan 채움

825     Queenstown
826    Southampton
827      Cherbourg
828     Queenstown
829      Cherbourg
830      Cherbourg
Name: embark_town, dtype: object

In [ ]:
df = pd.DataFrame({'c1':['a', 'a', 'b', 'a', 'b'],
                  'c2':[1, 1, 1, 2, 2],
                  'c3':[1, 1, 2, 2, 2]})

In [ ]:
df

  c1  c2  c3
0  a   1   1
1  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

In [ ]:
df_dup_first = df.duplicated()

In [ ]:
df_dup_first

0    False
1     True
2    False
3    False
4    False
dtype: bool

In [ ]:
df.c2.duplicated()

0    False
1     True
2     True
3    False
4     True
Name: c2, dtype: bool

In [ ]:
df2 = df.drop_duplicates()

In [ ]:
df2

  c1  c2  c3
0  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

In [ ]:
df3 = df.drop_duplicates(keep='last') # df2에서는 중복된 0 ,1에서 1행을 지웠는데 keep=last를 하고서는 0행이 지워짐 즉 중복된 행들중에 마지막 줄을 살려라

In [ ]:
df3

  c1  c2  c3
1  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

In [ ]:
df4 = df.drop_duplicates(keep=False) # 중복된 행들 전부 사라짐

In [ ]:
df4

  c1  c2  c3
2  b   1   2
3  a   2   2
4  b   2   2

In [ ]:
df.drop_duplicates(subset=['c2', 'c3']) # 뭐가 지워졌는지 파악하기

  c1  c2  c3
0  a   1   1
2  b   1   2
3  a   2   2

In [ ]:
df

  c1  c2  c3
0  a   1   1
1  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

In [ ]:
df.drop_duplicates(subset=['c2', 'c3'], keep=False)

  c1  c2  c3
2  b   1   2

In [ ]:
df = pd.read_csv('./drive/MyDrive/data/auto-mpg.csv', header=None)

In [ ]:
df

        0  1      2      3       4     5   6  7                          8
0    18.0  8  307.0  130.0  3504.0  12.0  70  1  chevrolet chevelle malibu
1    15.0  8  350.0  165.0  3693.0  11.5  70  1          buick skylark 320
2    18.0  8  318.0  150.0  3436.0  11.0  70  1         plymouth satellite
3    16.0  8  304.0  150.0  3433.0  12.0  70  1              amc rebel sst
4    17.0  8  302.0  140.0  3449.0  10.5  70  1                ford torino
..    ... ..    ...    ...     ...   ...  .. ..                        ...
393  27.0  4  140.0  86.00  2790.0  15.6  82  1            ford mustang gl
394  44.0  4   97.0  52.00  2130.0  24.6  82  2                  vw pickup
395  32.0  4  135.0  84.00  2295.0  11.6  82  1              dodge rampage
396  28.0  4  120.0  79.00  2625.0  18.6  82  1                ford ranger
397  31.0  4  119.0  82.00  2720.0  19.4  82  1                 chevy s-10

[398 rows x 9 columns]

In [ ]:
df.columns = ['mpg','cylinders','displacement','horsepower','weight',
              'acceleration','model year','origin','name']

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    float64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
 8   name          398 non-null    object
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB

In [ ]:
df.origin.unique()

array([1, 3, 2])

In [ ]:
df.horsepower.unique() # ? 고치기

array(['130.0', '165.0', '150.0', '140.0', '198.0', '220.0', '215.0',
       '225.0', '190.0', '170.0', '160.0', '95.00', '97.00', '85.00',
       '88.00', '46.00', '87.00', '90.00', '113.0', '200.0', '210.0',
       '193.0', '?', '100.0', '105.0', '175.0', '153.0', '180.0', '110.0',
       '72.00', '86.00', '70.00', '76.00', '65.00', '69.00', '60.00',
       '80.00', '54.00', '208.0', '155.0', '112.0', '92.00', '145.0',
       '137.0', '158.0', '167.0', '94.00', '107.0', '230.0', '49.00',
       '75.00', '91.00', '122.0', '67.00', '83.00', '78.00', '52.00',
       '61.00', '93.00', '148.0', '129.0', '96.00', '71.00', '98.00',
       '115.0', '53.00', '81.00', '79.00', '120.0', '152.0', '102.0',
       '108.0', '68.00', '58.00', '149.0', '89.00', '63.00', '48.00',
       '66.00', '139.0', '103.0', '125.0', '133.0', '138.0', '135.0',
       '142.0', '77.00', '62.00', '132.0', '84.00', '64.00', '74.00',
       '116.0', '82.00'], dtype=object)

In [ ]:
# ? 고치기
df['horsepower'] = df['horsepower'].replace('?', np.nan)

In [ ]:
df.horsepower.unique() # nan에 어떤 값을 넣어야 할까?

array(['130.0', '165.0', '150.0', '140.0', '198.0', '220.0', '215.0',
       '225.0', '190.0', '170.0', '160.0', '95.00', '97.00', '85.00',
       '88.00', '46.00', '87.00', '90.00', '113.0', '200.0', '210.0',
       '193.0', nan, '100.0', '105.0', '175.0', '153.0', '180.0', '110.0',
       '72.00', '86.00', '70.00', '76.00', '65.00', '69.00', '60.00',
       '80.00', '54.00', '208.0', '155.0', '112.0', '92.00', '145.0',
       '137.0', '158.0', '167.0', '94.00', '107.0', '230.0', '49.00',
       '75.00', '91.00', '122.0', '67.00', '83.00', '78.00', '52.00',
       '61.00', '93.00', '148.0', '129.0', '96.00', '71.00', '98.00',
       '115.0', '53.00', '81.00', '79.00', '120.0', '152.0', '102.0',
       '108.0', '68.00', '58.00', '149.0', '89.00', '63.00', '48.00',
       '66.00', '139.0', '103.0', '125.0', '133.0', '138.0', '135.0',
       '142.0', '77.00', '62.00', '132.0', '84.00', '64.00', '74.00',
       '116.0', '82.00'], dtype=object)

In [ ]:
# 데이터의 속성을 파악하고 어떤 값을 넣어야 할지 고민하기
# 이 데이터는 엔진 마력에 대한 데이터 인데 규칙도 없고 그 값을 정확하게 입력해야해서 평균값을 넣기보다 과감하게 제거하는게 나을것 같다
df = df.dropna(subset=['horsepower'], axis=0)

In [ ]:
df.horsepower.unique() # nan만 없앴다.

array(['130.0', '165.0', '150.0', '140.0', '198.0', '220.0', '215.0',
       '225.0', '190.0', '170.0', '160.0', '95.00', '97.00', '85.00',
       '88.00', '46.00', '87.00', '90.00', '113.0', '200.0', '210.0',
       '193.0', '100.0', '105.0', '175.0', '153.0', '180.0', '110.0',
       '72.00', '86.00', '70.00', '76.00', '65.00', '69.00', '60.00',
       '80.00', '54.00', '208.0', '155.0', '112.0', '92.00', '145.0',
       '137.0', '158.0', '167.0', '94.00', '107.0', '230.0', '49.00',
       '75.00', '91.00', '122.0', '67.00', '83.00', '78.00', '52.00',
       '61.00', '93.00', '148.0', '129.0', '96.00', '71.00', '98.00',
       '115.0', '53.00', '81.00', '79.00', '120.0', '152.0', '102.0',
       '108.0', '68.00', '58.00', '149.0', '89.00', '63.00', '48.00',
       '66.00', '139.0', '103.0', '125.0', '133.0', '138.0', '135.0',
       '142.0', '77.00', '62.00', '132.0', '84.00', '64.00', '74.00',
       '116.0', '82.00'], dtype=object)

In [ ]:
df['horsepower'] = df['horsepower'].astype('float') # 데이터 타입이 object였는데 실수로 바꿈

/tmp/ipykernel_911/3310907525.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['horsepower'] = df['horsepower'].astype('float') # 데이터 타입이 object였는데 실수로 바꿈

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 392 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           392 non-null    float64
 1   cylinders     392 non-null    int64
 2   displacement  392 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        392 non-null    float64
 5   acceleration  392 non-null    float64
 6   model year    392 non-null    int64
 7   origin        392 non-null    int64
 8   name          392 non-null    object
dtypes: float64(5), int64(3), object(1)
memory usage: 30.6+ KB

In [ ]:
df.horsepower

0      130.0
1      165.0
2      150.0
3      150.0
4      140.0
       ...
393     86.0
394     52.0
395     84.0
396     79.0
397     82.0
Name: horsepower, Length: 392, dtype: float64

In [ ]:
df.origin.unique()

array([1, 3, 2])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 392 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           392 non-null    float64
 1   cylinders     392 non-null    int64
 2   displacement  392 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        392 non-null    float64
 5   acceleration  392 non-null    float64
 6   model year    392 non-null    int64
 7   origin        392 non-null    int64
 8   name          392 non-null    object
dtypes: float64(5), int64(3), object(1)
memory usage: 30.6+ KB

In [ ]:
df['origin'] = df.origin.astype('category')

/tmp/ipykernel_911/4072339206.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['origin'] = df.origin.astype('category')

In [ ]:
df['origin']

0      1
1      1
2      1
3      1
4      1
      ..
393    1
394    2
395    1
396    1
397    1
Name: origin, Length: 392, dtype: category
Categories (3, int64): [1, 2, 3]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 392 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           392 non-null    float64
 1   cylinders     392 non-null    int64
 2   displacement  392 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        392 non-null    float64
 5   acceleration  392 non-null    float64
 6   model year    392 non-null    int64
 7   origin        392 non-null    category
 8   name          392 non-null    object
dtypes: category(1), float64(5), int64(2), object(1)
memory usage: 28.1+ KB

In [ ]:
df.origin.cat.codes

0      0
1      0
2      0
3      0
4      0
      ..
393    0
394    1
395    0
396    0
397    0
Length: 392, dtype: int8

In [ ]:
df.origin.cat.categories

Index([1, 2, 3], dtype='int64')

In [ ]:
titanic = sns.load_dataset('titanic')

In [ ]:
df = titanic.loc[:,['age', 'fare']][:10]

In [ ]:
df

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
7   2.0  21.0750
8  27.0  11.1333
9  14.0  30.0708

In [ ]:
def add_10(n):
    return n + 10

In [ ]:
def add_two_obj(a, b):
    return a - b

In [ ]:
df_10 = df.age.apply(add_10)

In [ ]:
df_10

0    32.0
1    48.0
2    36.0
3    45.0
4    45.0
5     NaN
6    64.0
7    12.0
8    37.0
9    24.0
Name: age, dtype: float64

In [ ]:
df_10.apply(add_two_obj, b=10)

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: age, dtype: float64

In [ ]:
df.age.apply(lambda n : n + 10)

0    32.0
1    48.0
2    36.0
3    45.0
4    45.0
5     NaN
6    64.0
7    12.0
8    37.0
9    24.0
Name: age, dtype: float64

In [ ]:
df.age.apply(lambda a, b : a - b, b = 10)

0    12.0
1    28.0
2    16.0
3    25.0
4    25.0
5     NaN
6    44.0
7    -8.0
8    17.0
9     4.0
Name: age, dtype: float64

In [ ]:
def over_thirty(age):
    return age > 30

In [ ]:
df.age.apply(over_thirty)

0    False
1     True
2    False
3     True
4     True
5    False
6     True
7    False
8    False
9    False
Name: age, dtype: bool

In [ ]:
df.age.map(over_thirty)

0    False
1     True
2    False
3     True
4     True
5    False
6     True
7    False
8    False
9    False
Name: age, dtype: bool

map : 시리즈에 적용.

apply : 시리즈, 데이터프레임 모두 적용.

applymap : 개별값에 적용할 때 주로 사용.

In [ ]:
df.age.map(lambda age : True if age > 30 else False)

0    False
1     True
2    False
3     True
4     True
5    False
6     True
7    False
8    False
9    False
Name: age, dtype: bool

In [ ]:
def calculate_stats(col):
    max_val = col.max()
    min_val = col.min()
    mean_val = col.mean()
    return pd.Series([max_val, min_val, mean_val], index=['maxs', 'mins', 'means'])

In [ ]:
result_df = df.apply(calculate_stats, axis=0)

In [ ]:
result_df

             age      fare
maxs   54.000000  71.28330
mins    2.000000   7.25000
means  28.111111  27.02082